import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, readFile, writeFile, symlink, rename } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SYNC_SCRIPT = path.join(REPO, 'scripts', 'sync.mjs')

async function fixture({ enabled = true, source = 'instructions/dsh-home.md', body = 'Default guidance.\n' } = {}) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'ohmydsh-agent-instructions-'))
  const repo = path.join(root, 'repo')
  const dshHome = path.join(root, 'dsh-home')
  await mkdir(path.join(repo, 'scripts'), { recursive: true })
  await mkdir(path.join(repo, 'instructions'), { recursive: true })
  await mkdir(path.join(dshHome, 'profiles', 'web'), { recursive: true })
  await writeFile(path.join(repo, 'scripts', 'sync.mjs'), await readFile(SYNC_SCRIPT))
  await mkdir(path.join(repo, 'scripts', 'lib'), { recursive: true })
  await writeFile(path.join(repo, 'scripts', 'lib', 'dsh-cli.mjs'), await readFile(path.join(REPO, 'scripts', 'lib', 'dsh-cli.mjs')))
  await symlink(path.join(REPO, 'node_modules'), path.join(repo, 'node_modules'), 'dir')
  await writeFile(path.join(repo, 'instructions', 'dsh-home.md'), body)
  await writeFile(
    path.join(dshHome, 'profiles', 'web', 'package.json'),
    JSON.stringify({ dependencies: {}, dsh: { profile: { bundles: [] } } }, null, 2) + '\n',
  )

  const writeManifest = async (config) => {
    const block = config === undefined
      ? ''
      : `agentInstructions:\n  enabled: ${String(config.enabled)}\n  source: ${config.source}\n`
    await writeFile(
      path.join(repo, 'dsh.yaml'),
      `dshVersion: 0.1.0-rc.6\ndependencies: []\n${block}customizations: []\n`,
    )
  }
  await writeManifest({ enabled, source })

  const runWithEnv = (extraEnv, ...args) => spawnSync(process.execPath, [path.join(repo, 'scripts', 'sync.mjs'), ...args], {
    cwd: repo,
    encoding: 'utf8',
    env: { ...process.env, DSH_BIN: '/usr/bin/true', ...extraEnv },
  })
  const run = (...args) => runWithEnv({ DSH_HOME: dshHome }, ...args)

  return { root, repo, dshHome, run, runWithEnv, writeManifest }
}

async function stateOf(dshHome) {
  return JSON.parse(await readFile(path.join(dshHome, '.dsh-sync-state.json'), 'utf8'))
}

test('deploys generated AGENTS.md, records provenance hash, and is idempotent', async () => {
  const fx = await fixture({ body: '# DSH guidance\n\nKeep permissions narrow.\n' })

  const first = fx.run()
  assert.equal(first.status, 0, first.stderr)
  const target = path.join(fx.dshHome, 'AGENTS.md')
  const deployed = await readFile(target, 'utf8')
  assert.match(deployed, /^# GENERATED by ohmydsh scripts\/sync\.mjs/m)
  assert.match(deployed, /Source: instructions\/dsh-home\.md/)
  assert.match(deployed, /Keep permissions narrow\./)
  const firstState = await stateOf(fx.dshHome)
  assert.equal(firstState.agentInstructions.source, 'instructions/dsh-home.md')
  assert.match(firstState.agentInstructions.deployedHash, /^[a-f0-9]{64}$/)

  const second = fx.run()
  assert.equal(second.status, 0, second.stderr)
  assert.match(second.stdout, /no changes/)
  assert.equal(await readFile(target, 'utf8'), deployed)
  assert.deepEqual((await stateOf(fx.dshHome)).agentInstructions, firstState.agentInstructions)
})

test('rejects absolute and repository-escaping instruction sources', async () => {
  for (const source of ['/tmp/AGENTS.md', '../outside.md', 'instructions/../../outside.md']) {
    const fx = await fixture({ source })
    const result = fx.run()
    assert.notEqual(result.status, 0, `${source} unexpectedly succeeded`)
    assert.match(result.stderr, /agentInstructions.*(relative|escape|repository)/i)
  }

  const fx = await fixture({ source: 'instructions/escaped.md' })
  const outside = path.join(path.dirname(fx.repo), 'outside.md')
  await writeFile(outside, 'outside repository\n')
  await symlink(outside, path.join(fx.repo, 'instructions', 'escaped.md'))
  const symlinkEscape = fx.run()
  assert.notEqual(symlinkEscape.status, 0, 'symlink escape unexpectedly succeeded')
  assert.match(symlinkEscape.stderr, /agentInstructions.*(escape|repository)/i)
})

test('refuses to overwrite an existing unmanaged AGENTS.md', async () => {
  const fx = await fixture()
  const target = path.join(fx.dshHome, 'AGENTS.md')
  await writeFile(target, 'hand-written instructions\n')

  const result = fx.run()

  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /unmanaged|not managed/i)
  assert.equal(await readFile(target, 'utf8'), 'hand-written instructions\n')
  assert.equal((await stateOf(fx.dshHome)).agentInstructions, undefined)
})

test('refuses managed-content drift on update and disable', async () => {
  const fx = await fixture()
  assert.equal(fx.run().status, 0)
  const target = path.join(fx.dshHome, 'AGENTS.md')
  const stateBefore = (await stateOf(fx.dshHome)).agentInstructions
  await writeFile(target, 'locally edited\n')
  await writeFile(path.join(fx.repo, 'instructions', 'dsh-home.md'), 'new source\n')

  const update = fx.run()
  assert.notEqual(update.status, 0)
  assert.match(update.stderr, /drift|changed/i)
  assert.equal(await readFile(target, 'utf8'), 'locally edited\n')
  assert.deepEqual((await stateOf(fx.dshHome)).agentInstructions, stateBefore)

  await fx.writeManifest({ enabled: false, source: 'instructions/dsh-home.md' })
  const disable = fx.run()
  assert.notEqual(disable.status, 0)
  assert.equal(await readFile(target, 'utf8'), 'locally edited\n')
  assert.deepEqual((await stateOf(fx.dshHome)).agentInstructions, stateBefore)
})

test('disabled, deleted, and reset configurations remove only matching managed output', async () => {
  for (const mode of ['disabled', 'deleted', 'reset']) {
    const fx = await fixture()
    assert.equal(fx.run().status, 0)
    if (mode === 'disabled') await fx.writeManifest({ enabled: false, source: 'instructions/dsh-home.md' })
    if (mode === 'deleted') await fx.writeManifest(undefined)

    const result = mode === 'reset' ? fx.run('--reset') : fx.run()

    assert.equal(result.status, 0, result.stderr)
    assert.equal(existsSync(path.join(fx.dshHome, 'AGENTS.md')), false, `${mode} left AGENTS.md behind`)
    assert.equal((await stateOf(fx.dshHome)).agentInstructions, undefined)
  }
})

test('blank DSH_HOME falls back to the default home instead of the filesystem root', async () => {
  const fx = await fixture()
  const fakeHome = path.join(fx.root, 'user-home')
  const defaultDshHome = path.join(fakeHome, '.dsh')
  await mkdir(path.join(defaultDshHome, 'profiles', 'web'), { recursive: true })
  await writeFile(
    path.join(defaultDshHome, 'profiles', 'web', 'package.json'),
    JSON.stringify({ dependencies: {}, dsh: { profile: { bundles: [] } } }, null, 2) + '\n',
  )

  const result = fx.runWithEnv({ HOME: fakeHome, DSH_HOME: '   ' })

  assert.equal(result.status, 0, result.stderr)
  assert.equal(existsSync(path.join(defaultDshHome, 'AGENTS.md')), true)
})

test('adopts sync state written under a previous repository name', async () => {
  // Regression: renaming the repo used to rename the state file too, orphaning
  // the ledger. Sync then saw a managed AGENTS.md as unmanaged and fail-closed,
  // which also rolled back the launcher's DSH upgrade.
  const fx = await fixture({ body: '# DSH guidance\n\nKeep permissions narrow.\n' })
  assert.equal(fx.run().status, 0)

  const target = path.join(fx.dshHome, 'AGENTS.md')
  const current = path.join(fx.dshHome, '.dsh-sync-state.json')
  const legacy = path.join(fx.dshHome, '.mydsh-sync-state.json')
  // Recreate the pre-rename layout: state under the old name, and a deployed
  // AGENTS.md whose GENERATED header still carries the old repository name.
  await rename(current, legacy)
  const stale = (await readFile(target, 'utf8')).replace('GENERATED by ohmydsh', 'GENERATED by mydsh')
  await writeFile(target, stale)
  const legacyState = JSON.parse(await readFile(legacy, 'utf8'))
  legacyState.agentInstructions.deployedHash = createHash('sha256').update(stale).digest('hex')
  await writeFile(legacy, JSON.stringify(legacyState, null, 2) + '\n')

  const result = fx.run()

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /migrate sync state \.mydsh-sync-state\.json -> \.dsh-sync-state\.json/)
  assert.equal(existsSync(legacy), false, 'legacy state should be renamed, not copied')
  // Ownership survived: the stale header is rewritten instead of refused.
  const deployed = await readFile(target, 'utf8')
  assert.match(deployed, /^# GENERATED by ohmydsh scripts\/sync\.mjs/m)
  const state = await stateOf(fx.dshHome)
  assert.equal(state.agentInstructions.deployedHash, createHash('sha256').update(deployed).digest('hex'))

  const again = fx.run()
  assert.equal(again.status, 0, again.stderr)
  assert.match(again.stdout, /no changes/)
})

test('reports superseded legacy state files without deleting them', async () => {
  const fx = await fixture()
  assert.equal(fx.run().status, 0)

  const current = path.join(fx.dshHome, '.dsh-sync-state.json')
  const newer = path.join(fx.dshHome, '.ohmydsh-sync-state.json')
  const older = path.join(fx.dshHome, '.mydsh-sync-state.json')
  await rename(current, newer)
  await writeFile(older, JSON.stringify({ agentInstructions: { source: 'stale', deployedHash: 'stale' } }, null, 2) + '\n')

  const result = fx.run()

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /migrate sync state \.ohmydsh-sync-state\.json/)
  assert.match(result.stdout, /ignoring superseded sync state \.mydsh-sync-state\.json/)
  assert.equal(existsSync(older), true, 'older state must be reported, never deleted')
  // The newest generation won: its bookkeeping is what got adopted.
  assert.equal((await stateOf(fx.dshHome)).agentInstructions.source, 'instructions/dsh-home.md')
})
