#!/usr/bin/env node
// zydsh sync — materialize dsh.yaml customizations into ~/.dsh.
// Idempotent; the repository (dsh.yaml + customization dirs) is the source of truth.
import { readFile, writeFile, mkdir, cp, rm, readdir, stat } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DSH_HOME = process.env.DSH_HOME ?? path.join(os.homedir(), '.dsh')
const PROFILE = process.env.DSH_PROFILE ?? 'web'
const PROFILE_DIR = path.join(DSH_HOME, 'profiles', PROFILE)
const STATE_FILE = path.join(DSH_HOME, '.zydsh-sync-state.json')
const GENERATED_HEADER = `# GENERATED by zydsh scripts/sync.mjs — do not edit by hand.\n# Source of truth: ${REPO}/dsh.yaml and patches/. Edit there, then re-run sync.\n`

const failures = []
const changes = []
const log = (msg) => console.log(`[sync] ${msg}`)
const change = (msg) => { changes.push(msg); log(msg) }
const fail = (msg) => { failures.push(msg); console.error(`[sync] ERROR ${msg}`) }

// ---------- manifest ----------
function loadManifest() {
  const file = path.join(REPO, 'dsh.yaml')
  if (!existsSync(file)) {
    throw new Error(`manifest missing: ${file} — create it first (see README.md)`)
  }
  const doc = yaml.load(readFileSync(file, 'utf8'))
  if (typeof doc !== 'object' || doc === null) throw new Error(`manifest ${file} is empty or not a YAML mapping`)
  if (typeof doc.dshVersion !== 'string' || doc.dshVersion === '') throw new Error('manifest: dshVersion is required')
  if (!Array.isArray(doc.customizations)) throw new Error('manifest: customizations must be a list')
  const items = doc.customizations.map((item, index) => {
    const label = `customizations[${index}]`
    if (typeof item.id !== 'string' || !/^[a-z0-9][a-z0-9._-]*$/i.test(item.id)) throw new Error(`${label}: valid string id required`)
    if (!['package', 'preset', 'patch', 'skill'].includes(item.type)) throw new Error(`${label} (${item.id}): type must be package|preset|patch|skill`)
    const source = item.source ?? 'local'
    if (!['local', 'remote'].includes(source)) throw new Error(`${label} (${item.id}): source must be local|remote`)
    if (source === 'remote' && item.type !== 'package') throw new Error(`${label} (${item.id}): source remote only applies to type package`)
    if (item.type === 'package' && source === 'remote' && typeof item.spec !== 'string') throw new Error(`${label} (${item.id}): remote package requires spec`)
    if ((item.type === 'package' || item.type === 'preset') && typeof item.version !== 'string') throw new Error(`${label} (${item.id}): package/preset requires version`)
    return { ...item, source, enabled: item.enabled !== false }
  })
  return { dshVersion: doc.dshVersion, items }
}

// ---------- helpers ----------
function readJson(file) {
  try { return JSON.parse(readFileSync(file, 'utf8')) } catch { return undefined }
}

async function writeJson(file, value) {
  await writeFile(file, JSON.stringify(value, null, 2) + '\n')
}

async function dirHash(dir) {
  const entries = await collectFiles(dir)
  const h = createHash('sha256')
  for (const rel of entries.sort()) {
    h.update(rel + '\0')
    h.update(await readFile(path.join(dir, rel)))
  }
  return h.digest('hex')
}

async function collectFiles(dir, base = dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await collectFiles(full, base))
    else if (entry.isFile()) out.push(path.relative(base, full))
  }
  return out
}

async function loadState() {
  return readJson(STATE_FILE) ?? {}
}

async function saveState(state) {
  await mkdir(path.dirname(STATE_FILE), { recursive: true })
  await writeJson(STATE_FILE, state)
}

function dshCli(args, opts = {}) {
  const base = process.env.DSH_BIN
    ? [process.env.DSH_BIN]
    : ['npx', '-y', `@deepseek-ai/dsh@${opts.version}`]
  const r = spawnSync(base[0], [...base.slice(1), ...args], { stdio: 'inherit' })
  return r.status === 0
}

function npmNameOf(item) {
  if (item.source === 'local') {
    const pkg = readJson(path.join(REPO, 'packages', item.id, 'package.json'))
    if (pkg === undefined) throw new Error(`package ${item.id}: packages/${item.id}/package.json missing`)
    return pkg.name
  }
  const m = String(item.spec).match(/^(@[^/@]+\/[^/@]+|[^/@]+)@/)
  return m ? m[1] : String(item.spec)
}

function installedVersion(name) {
  const pkg = readJson(path.join(PROFILE_DIR, 'node_modules', ...name.split('/'), 'package.json'))
  return pkg?.version
}

// ---------- actions ----------
async function syncPackages(manifest, items) {
  const packages = items.filter((i) => i.type === 'package')
  const enabled = packages.filter((i) => i.enabled)
  const profilePkgPath = path.join(PROFILE_DIR, 'package.json')
  const profilePkg = readJson(profilePkgPath)
  if (profilePkg === undefined) return fail(`profile package.json missing at ${PROFILE_DIR}`)

  const names = new Map()
  for (const item of packages) {
    try { names.set(item.id, npmNameOf(item)) } catch (e) { fail(String(e.message ?? e)) }
  }
  const enabledNames = enabled.map((i) => names.get(i.id)).filter(Boolean)

  // remove disabled / missing ones first
  for (const [id, name] of names) {
    const item = packages.find((i) => i.id === id)
    if (item.enabled) continue
    if (installedVersion(name) !== undefined) {
      change(`remove disabled package ${name}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove ${name}`)
    }
  }

  // install / pin-check enabled ones
  for (const item of enabled) {
    const name = names.get(item.id)
    const spec = item.source === 'local' ? `file:${path.join(REPO, 'packages', item.id)}` : item.spec
    const current = installedVersion(name)
    if (current !== undefined && item.source === 'remote' && current !== item.version) {
      change(`version drift ${name} ${current} -> ${item.version}, re-adding`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', `${name}@${item.version}`], { version: manifest.dshVersion })) fail(`failed to pin ${name}`)
    } else if (current !== undefined && item.source === 'local' && current !== item.version) {
      change(`local package ${name} ${current} -> ${item.version}, re-adding`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', spec], { version: manifest.dshVersion })) fail(`failed to reinstall ${name}`)
    } else if (current === undefined) {
      change(`install ${item.source} package ${name} (${spec})`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', spec], { version: manifest.dshVersion })) fail(`failed to install ${name}`)
    } else {
      log(`package ${name}@${current} up-to-date`)
    }
  }

  // normalize bundles: shipped base (non-managed) entries first, then enabled managed in manifest order
  const refreshed = readJson(profilePkgPath)
  if (refreshed !== undefined) {
    const managed = new Set([...names.values()])
    const base = (refreshed.dsh?.profile?.bundles ?? []).filter((b) => !managed.has(b))
    const bundles = [...base, ...enabledNames]
    const before = JSON.stringify(refreshed.dsh?.profile?.bundles ?? [])
    refreshed.dsh ??= {}
    refreshed.dsh.profile ??= {}
    refreshed.dsh.profile.bundles = bundles
    if (JSON.stringify(bundles) !== before) {
      change(`bundles: [${bundles.join(', ')}]`)
      await writeJson(profilePkgPath, refreshed)
    }
  }
}

async function syncDirs(manifest, items, type, srcDir, dstRoot, requiredFile, label) {
  const state = await loadState()
  const managed = items.filter((i) => i.type === type)
  const enabled = managed.filter((i) => i.enabled)
  for (const item of enabled) {
    const src = path.join(REPO, srcDir, item.id)
    const dst = path.join(dstRoot, item.id)
    if (!existsSync(path.join(src, requiredFile))) {
      fail(`${label} ${item.id}: ${path.join(srcDir, item.id)}/${requiredFile} missing`)
      continue
    }
    const hash = await dirHash(src)
    if (state[`${type}:${item.id}`] === hash && existsSync(path.join(dst, requiredFile))) {
      log(`${label} ${item.id} up-to-date`)
      continue
    }
    change(`copy ${label} ${item.id} -> ${dst}`)
    await rm(dst, { recursive: true, force: true })
    await mkdir(path.dirname(dst), { recursive: true })
    await cp(src, dst, { recursive: true })
    state[`${type}:${item.id}`] = hash
  }
  for (const item of managed.filter((i) => !i.enabled)) {
    const key = `${type}:${item.id}`
    if (state[key] !== undefined) {
      const dst = path.join(dstRoot, item.id)
      if (existsSync(dst)) {
        change(`remove disabled ${label} ${item.id}`)
        await rm(dst, { recursive: true, force: true })
      }
      delete state[key]
    }
  }
  await saveState(state)
}

async function syncPatches(items) {
  const fragments = items.filter((i) => i.type === 'patch' && i.enabled)
  const target = path.join(PROFILE_DIR, 'cordis.patch.yml')
  let body = '[]\n'
  if (fragments.length > 0) {
    const parts = []
    for (const item of fragments) {
      const file = path.join(REPO, 'patches', `${item.id}.yml`)
      if (!existsSync(file)) {
        fail(`patch ${item.id}: patches/${item.id}.yml missing`)
        continue
      }
      parts.push(`# --- fragment: ${item.id} ---\n` + readFileSync(file, 'utf8').trimEnd() + '\n')
    }
    body = parts.join('\n')
  }
  const content = GENERATED_HEADER + '\n' + body
  const existing = existsSync(target) ? readFileSync(target, 'utf8') : ''
  if (existing === content) {
    log('patches up-to-date')
    return
  }
  change(`generate ${target}`)
  if (existing !== '') await writeFile(target + '.bak', existing)
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, content)
}

function checkDshVersion(manifest) {
  const fish = path.join(REPO, 'scripts', 'dsh.fish')
  if (!existsSync(fish)) return
  const m = readFileSync(fish, 'utf8').match(/set -g DSH_VERSION (.+)/)
  if (m && m[1] !== manifest.dshVersion) {
    console.error(`[sync] WARN scripts/dsh.fish pins DSH_VERSION ${m[1]} but dsh.yaml says ${manifest.dshVersion}`)
  }
}

// ---------- main ----------
async function main() {
  const manifest = loadManifest()
  await mkdir(PROFILE_DIR, { recursive: true })
  await syncPackages(manifest, manifest.items)
  await syncDirs(manifest, manifest.items, 'preset', 'presets', path.join(DSH_HOME, '.agent-presets'), 'cordis.yml', 'preset')
  await syncDirs(manifest, manifest.items, 'skill', 'skills', path.join(DSH_HOME, 'skills'), 'SKILL.md', 'skill')
  await syncPatches(manifest.items)
  checkDshVersion(manifest)
  console.log('')
  if (failures.length > 0) {
    console.error(`[sync] finished with ${failures.length} failure(s):`)
    for (const f of failures) console.error(`  - ${f}`)
    process.exitCode = 1
    return
  }
  if (changes.length === 0) log('no changes — deployment already matches manifest')
  else log(`done — ${changes.length} change(s) applied`)
}

main().catch((error) => {
  console.error(`[sync] ERROR ${String(error?.message ?? error)}`)
  process.exitCode = 1
})
