#!/usr/bin/env node
// ohmydsh sync — materialize dsh.yaml customizations into ~/.dsh.
// Idempotent; the repository (dsh.yaml + customization dirs) is the source of truth.
import { readFile, writeFile, mkdir, cp, rm, readdir, stat, rename, realpath } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'
import { runDshCli } from './lib/dsh-cli.mjs'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DSH_HOME = resolveDshHome(process.env.DSH_HOME)
const PROFILE = process.env.DSH_PROFILE ?? 'web'
const PROFILE_DIR = path.join(DSH_HOME, 'profiles', PROFILE)
// Deployment bookkeeping. The filename is deliberately independent of the
// repository name: it used to carry it (.zydsh- / .mydsh- / .ohmydsh-), so every
// repo rename orphaned the state and sync restarted with an empty ledger —
// silently re-adopting most artifacts, but hard-failing on the fail-closed
// AGENTS.md path. Legacy names are migrated on startup, newest generation first.
const STATE_FILE = path.join(DSH_HOME, '.dsh-sync-state.json')
const LEGACY_STATE_FILES = ['.ohmydsh-sync-state.json', '.mydsh-sync-state.json', '.zydsh-sync-state.json']
const GENERATED_HEADER = `# GENERATED by ohmydsh scripts/sync.mjs — do not edit by hand.\n# Source of truth: ${REPO}/dsh.yaml and patches/. Edit there, then re-run sync.\n`

/**
 * Truthy/falsy spellings accepted for a boolean env override. Shared by the
 * per-customization `enabledEnv` field, so every mechanism carries the same
 * meaning for the same spellings.
 */
const ENV_BOOL_TRUE = new Set(['1', 'true', 'yes', 'on'])
const ENV_BOOL_FALSE = new Set(['0', 'false', 'no', 'off'])

/**
 * Resolve a boolean env override: unset/blank/unrecognized returns undefined
 * so the caller falls back to its manifest-declared default; a recognized
 * truthy/falsy spelling (case-insensitive) returns true/false. Used by the
 * per-customization `enabledEnv` field (loadManifest).
 */
function resolveEnabledOverride(raw) {
  if (raw === undefined) return undefined
  const v = raw.trim().toLowerCase()
  if (v === '') return undefined
  if (ENV_BOOL_TRUE.has(v)) return true
  if (ENV_BOOL_FALSE.has(v)) return false
  return undefined
}

const failures = []
const changes = []
const log = (msg) => console.log(`[sync] ${msg}`)
const change = (msg) => { changes.push(msg); log(msg) }
const fail = (msg) => { failures.push(msg); console.error(`[sync] ERROR ${msg}`) }

// ---------- manifest ----------
function loadManifest() {
  const file = path.join(REPO, 'dsh.yaml')
  if (!existsSync(file)) {
    throw new Error(`manifest missing: ${file} — create it first (see README.md)`)
  }
  const doc = yaml.load(readFileSync(file, 'utf8'))
  if (typeof doc !== 'object' || doc === null) throw new Error(`manifest ${file} is empty or not a YAML mapping`)
  if (typeof doc.dshVersion !== 'string' || doc.dshVersion === '') throw new Error('manifest: dshVersion is required')
  if (!Array.isArray(doc.customizations)) throw new Error('manifest: customizations must be a list')

  // top-level dependencies: bundle-less support packages (exact-version npm specs)
  const deps = (doc.dependencies ?? []).map((spec, index) => {
    const label = `dependencies[${index}]`
    if (typeof spec !== 'string') throw new Error(`${label}: must be a string npm spec with exact version`)
    const parsed = parseSpec(spec)
    if (parsed === undefined) throw new Error(`${label}: "${spec}" — expected "<name>@<version>"`)
    return { ...parsed, spec }
  })
  const depNames = new Set(deps.map((d) => d.name))

  const items = doc.customizations.map((item, index) => {
    const label = `customizations[${index}]`
    if (typeof item.id !== 'string' || !/^[a-z0-9][a-z0-9._-]*$/i.test(item.id)) throw new Error(`${label}: valid string id required`)
    if (!['package', 'preset', 'patch', 'skill'].includes(item.type)) throw new Error(`${label} (${item.id}): type must be package|preset|patch|skill`)
    const source = item.source ?? 'local'
    if (!['local', 'remote'].includes(source)) throw new Error(`${label} (${item.id}): source must be local|remote`)
    if (source === 'remote' && item.type !== 'package') throw new Error(`${label} (${item.id}): source remote only applies to type package`)
    if (item.type === 'package' && source === 'remote' && typeof item.spec !== 'string') throw new Error(`${label} (${item.id}): remote package requires spec`)
    if (item.name !== undefined && (typeof item.name !== 'string' || !/^(@[^/@]+\/[^/@]+|[^/@]+)$/.test(item.name))) throw new Error(`${label} (${item.id}): name must be a valid npm package name`)
    if (item.type === 'package' && source === 'remote' && parseSpec(item.spec) === undefined && item.name === undefined) throw new Error(`${label} (${item.id}): remote package with a non-npm spec requires an explicit name (real npm package name)`)
    if ((item.type === 'package' || item.type === 'preset') && typeof item.version !== 'string') throw new Error(`${label} (${item.id}): package/preset requires version`)
    // deps: ownership references into the top-level dependencies list (not an install source)
    if (item.deps !== undefined) {
      if (!Array.isArray(item.deps) || item.deps.some((d) => typeof d !== 'string')) throw new Error(`${label} (${item.id}): deps must be a list of package names`)
      for (const name of item.deps) {
        if (!depNames.has(name)) throw new Error(`${label} (${item.id}): deps references "${name}" which is missing from top-level dependencies`)
      }
    }
    // A local bundle may build a fixed-source compatibility package that must
    // resolve under an existing official package identity. It is installed in
    // the same pnpm transaction as its owner and removed with that owner.
    let buildInputs
    if (item.buildInputs !== undefined) {
      if (source !== 'local' || !Array.isArray(item.buildInputs) || item.buildInputs.some(entry => typeof entry !== 'string' || entry === '' || path.isAbsolute(entry))) {
        throw new Error(`${label} (${item.id}): buildInputs must be relative repo paths on a local customization`)
      }
      buildInputs = item.buildInputs.map((entry, inputIndex) => {
        const normalized = path.normalize(entry)
        if (normalized === '..' || normalized.startsWith(`..${path.sep}`)) throw new Error(`${label} (${item.id}).buildInputs[${inputIndex}]: path must stay inside the repository`)
        return normalized
      })
    }
    let compatDependencies
    if (item.compatDependencies !== undefined) {
      if (item.type !== 'package' || source !== 'local' || !Array.isArray(item.compatDependencies)) {
        throw new Error(`${label} (${item.id}): compatDependencies is only valid as a list on local packages`)
      }
      compatDependencies = item.compatDependencies.map((entry, compatIndex) => {
        const compatLabel = `${label} (${item.id}).compatDependencies[${compatIndex}]`
        if (typeof entry !== 'object' || entry === null || Array.isArray(entry)) throw new Error(`${compatLabel}: mapping required`)
        if (typeof entry.name !== 'string' || !/^(@[^/@]+\/[^/@]+|[^/@]+)$/.test(entry.name)) throw new Error(`${compatLabel}: valid npm package name required`)
        if (typeof entry.path !== 'string' || entry.path === '' || path.isAbsolute(entry.path)) throw new Error(`${compatLabel}: path must be a non-empty relative path`)
        const normalized = path.normalize(entry.path)
        if (normalized === '..' || normalized.startsWith(`..${path.sep}`)) throw new Error(`${compatLabel}: path must stay inside the owner package`)
        if (depNames.has(entry.name)) throw new Error(`${compatLabel}: conflicts with top-level dependency ${entry.name}`)
        return { name: entry.name, path: normalized }
      })
    }
    // enabledEnv: optional per-customization env override of `enabled`,
    // machine-specific opt-in without touching dsh.yaml.
    // Validated eagerly (fail closed) so a typo'd env name doesn't silently
    // degrade into "the switch never seems to work" with no diagnostic.
    let enabled = item.enabled !== false
    if (item.enabledEnv !== undefined) {
      if (typeof item.enabledEnv !== 'string' || !/^DSH_[A-Z0-9_]+$/.test(item.enabledEnv)) {
        throw new Error(`${label} (${item.id}): enabledEnv must be an uppercase DSH_-prefixed env var name (e.g. DSH_${item.id.toUpperCase().replace(/[^A-Z0-9]+/g, '_')})`)
      }
      const override = resolveEnabledOverride(process.env[item.enabledEnv])
      if (override !== undefined) enabled = override
    }
    return { ...item, source, enabled, buildInputs, compatDependencies }
  })
  const web = doc.web ?? {}
  if (typeof web !== 'object' || web === null || Array.isArray(web)) {
    throw new Error('manifest: web must be a mapping (web.open: true|false)')
  }
  if (web.open !== undefined && typeof web.open !== 'boolean') {
    throw new Error('manifest: web.open must be a boolean')
  }
  const agentInstructions = validateAgentInstructions(doc.agentInstructions)
  return { dshVersion: doc.dshVersion, items, deps, agentInstructions, web: { open: web.open !== false } }
}

function validateAgentInstructions(value) {
  if (value === undefined) return undefined
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('manifest: agentInstructions must be a mapping with enabled and source')
  }
  if (typeof value.enabled !== 'boolean') throw new Error('manifest: agentInstructions.enabled must be a boolean')
  if (typeof value.source !== 'string' || value.source.trim() === '') {
    throw new Error('manifest: agentInstructions.source must be a non-empty repository-relative path')
  }
  const source = value.source.trim()
  if (path.isAbsolute(source)) throw new Error('manifest: agentInstructions.source must be a repository-relative path, not an absolute path')
  const sourcePath = path.resolve(REPO, source)
  const relative = path.relative(REPO, sourcePath)
  if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error('manifest: agentInstructions.source must not escape the repository')
  }
  return { enabled: value.enabled, source: relative.split(path.sep).join('/'), sourcePath }
}

function parseSpec(spec) {
  const m = String(spec).match(/^(@[^/@]+\/[^/@]+|[^/@]+)@(.+)$/)
  if (m === null || m[2] === '') return undefined
  return { name: m[1], version: m[2] }
}

// ---------- helpers ----------
function resolveDshHome(value) {
  const configured = typeof value === 'string' ? value.trim() : ''
  if (configured === '') return path.join(os.homedir(), '.dsh')
  if (configured === '~') return os.homedir()
  if (configured.startsWith(`~${path.sep}`) || configured.startsWith('~/')) {
    return path.resolve(os.homedir(), configured.slice(2))
  }
  return path.resolve(configured)
}

function readJson(file) {
  try { return JSON.parse(readFileSync(file, 'utf8')) } catch { return undefined }
}

async function writeJson(file, value) {
  await writeFile(file, JSON.stringify(value, null, 2) + '\n')
}

function contentHash(content) {
  return createHash('sha256').update(content).digest('hex')
}

async function atomicWrite(file, content) {
  await mkdir(path.dirname(file), { recursive: true })
  const temp = path.join(path.dirname(file), `.${path.basename(file)}.tmp-${process.pid}-${Date.now()}`)
  try {
    await writeFile(temp, content, { flag: 'wx' })
    await rename(temp, file)
  } finally {
    await rm(temp, { force: true })
  }
}

async function filesHash(dir, options = {}) {
  const entries = await collectFiles(dir, dir, options)
  const h = createHash('sha256')
  for (const rel of entries.sort()) {
    h.update(rel + '\0')
    h.update(await readFile(path.join(dir, rel)))
  }
  return h.digest('hex')
}

async function dirHash(dir) {
  return filesHash(dir)
}

async function collectFiles(dir, base = dir, options = {}) {
  const out = []
  const excludeDirs = new Set(options.excludeDirs ?? [])
  const excludeFiles = new Set(options.excludeFiles ?? [])
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = path.relative(base, path.join(dir, entry.name)).split(path.sep).join('/')
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
    if (entry.isDirectory() && excludeDirs.has(rel)) continue
    if (entry.isFile() && (excludeFiles.has(entry.name) || excludeFiles.has(rel))) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await collectFiles(full, base, options))
    else if (entry.isFile()) out.push(path.relative(base, full))
  }
  return out
}

async function localBuildInputHash(dir, extraInputs = []) {
  const entries = await collectFiles(dir, dir, {
    excludeDirs: ['lib', 'node_modules', 'test', 'tests', 'checking', 'coverage'],
    excludeFiles: ['package-lock.json', 'npm-debug.log'],
  })
  const selected = entries.filter((rel) => {
    const normalized = rel.split(path.sep).join('/')
    const base = path.posix.basename(normalized)
    return normalized.startsWith('src/') ||
      normalized === 'package.json' ||
      (!normalized.includes('/') && /\.mjs$/.test(normalized)) ||
      /^tsconfig(?:\..+)?\.json$/.test(base) ||
      /^(?:tsdown|vite|rollup|esbuild)\.config\.[cm]?[jt]s$/.test(base)
  })
  const h = createHash('sha256')
  h.update(`node:${process.version}\0`)
  for (const rel of selected.sort()) {
    h.update(rel + '\0')
    h.update(await readFile(path.join(dir, rel)))
  }
  for (const input of [...extraInputs].sort()) {
    const absolute = path.join(REPO, input)
    const inputStat = await stat(absolute).catch(() => undefined)
    if (inputStat === undefined || !inputStat.isFile()) throw new Error(`local build input missing or not a regular file: ${input}`)
    h.update(`repo:${input}\0`)
    h.update(await readFile(absolute))
  }
  return h.digest('hex')
}

async function installContentHashOf(dir, pkg) {
  const included = new Set(['package.json', pkg?.dsh?.bundle?.patch, ...(pkg?.files ?? [])].filter(Boolean))
  const entries = await collectFiles(dir, dir, {
    excludeDirs: Array.isArray(pkg?.files) && pkg.files.length > 0
      ? ['node_modules', 'src', 'test', 'tests', 'checking', 'coverage']
      : ['node_modules', 'test', 'tests', 'checking', 'coverage'],
    excludeFiles: ['package-lock.json', 'tsconfig.json', 'tsconfig.client.json', 'tsdown.config.ts', 'vitest.config.ts'],
  })
  const selected = Array.isArray(pkg?.files) && pkg.files.length > 0
    ? entries.filter((rel) => {
        const normalized = rel.split(path.sep).join('/')
        return [...included].some((item) => normalized === item || normalized.startsWith(`${item}/`))
      })
    : entries
  const h = createHash('sha256')
  for (const rel of selected.sort()) {
    h.update(rel + '\0')
    h.update(await readFile(path.join(dir, rel)))
  }
  return h.digest('hex')
}

async function localInstallContentHash(dir) {
  const pkg = readJson(path.join(dir, 'package.json'))
  return installContentHashOf(dir, pkg)
}

/**
 * Content hash of a deployed local package, using the SOURCE manifest's
 * publishable-set contract (the deployed package.json may have been
 * rewritten by pnpm). The deployment directory must exist; absence is
 * reported as null (the missing-files repair path owns directory creation).
 */
async function deployedContentHash(sourcePkg, name) {
  const deployedDir = path.join(PROFILE_DIR, 'node_modules', ...name.split('/'))
  if (!existsSync(deployedDir)) return null
  return installContentHashOf(deployedDir, sourcePkg)
}

/**
 * Force-refresh a deployed local package. pnpm treats `file:` directory
 * dependencies as merge-without-overwrite: a plain re-add keeps every
 * already-present subtree file (lib/*) stale. Evicting the deployed copy
 * first forces fresh materialization. Atomic: on failure (or when the
 * re-verified bytes still mismatch the source) the previous deployment is
 * restored and false is returned — never a half-deployed state.
 */
async function refreshLocalDeployment(localDir, name, spec, compatSpecs, expectedHash, dshVersion) {
  const deployedDir = path.join(PROFILE_DIR, 'node_modules', ...name.split('/'))
  const quarantine = `${deployedDir}.ohmydsh-refresh`
  const sourcePkg = readJson(path.join(localDir, 'package.json'))
  await rm(quarantine, { recursive: true, force: true })
  await rename(deployedDir, quarantine).catch(() => {})
  const installed = dshCli(['plugin', '--profile', PROFILE, 'add', ...compatSpecs, spec], { version: dshVersion })
  if (!installed) {
    // add failed: restore the previous deployment (nothing else was touched).
    if (!existsSync(deployedDir) && existsSync(quarantine)) {
      await rename(quarantine, deployedDir).catch(() => {})
      log(`restored previous deployment of ${name} after failed refresh`)
    }
    return false
  }
  const deployedHash = await deployedContentHash(sourcePkg, name)
  if (deployedHash === null || deployedHash !== expectedHash) {
    // add "succeeded" but the deployed bytes still do not match the source
    // (e.g. pnpm merging from a cached/stale pack): restore, never accept.
    await rm(deployedDir, { recursive: true, force: true })
    if (existsSync(quarantine)) {
      await rename(quarantine, deployedDir).catch(() => {})
      log(`restored previous deployment of ${name} after refresh verification mismatch`)
    }
    return false
  }
  await rm(quarantine, { recursive: true, force: true })
  return true
}

function localBuildOutputsExist(dir, pkg) {
  if (typeof pkg?.scripts?.build !== 'string') return true
  const files = Array.isArray(pkg.files) ? pkg.files : []
  const outputRoots = files.filter((entry) => typeof entry === 'string' && entry !== '')
  if (outputRoots.length === 0) return existsSync(path.join(dir, 'lib'))
  return outputRoots.every((entry) => existsSync(path.join(dir, entry)))
}

function runLocalBuild(item, dir) {
  const pkg = readJson(path.join(dir, 'package.json'))
  if (typeof pkg?.scripts?.build !== 'string') return true
  change(`build local package ${pkg.name ?? item.id}`)
  const result = spawnSync('npm', ['run', 'build', '--workspace', pkg.name], {
    cwd: REPO,
    stdio: 'inherit',
  })
  if (result.status === 0) return true
  fail(`local package ${pkg.name ?? item.id}: npm run build --workspace ${pkg.name} failed before deployment`)
  return false
}

/**
 * Adopt the state written under a previous repository name. Runs before any
 * state read: renaming (not copying) the newest legacy ledger keeps ownership
 * of already-deployed artifacts across a repo rename. Older generations are
 * left in place and only reported — this function never deletes.
 */
async function migrateLegacyState() {
  if (existsSync(STATE_FILE)) return
  const present = LEGACY_STATE_FILES.map(name => path.join(DSH_HOME, name)).filter(existsSync)
  if (present.length === 0) return
  const [newest, ...older] = present
  await mkdir(path.dirname(STATE_FILE), { recursive: true })
  await rename(newest, STATE_FILE)
  change(`migrate sync state ${path.basename(newest)} -> ${path.basename(STATE_FILE)}`)
  for (const stale of older) log(`ignoring superseded sync state ${path.basename(stale)} (safe to delete)`)
}

async function loadState() {
  return readJson(STATE_FILE) ?? {}
}

async function saveState(state) {
  await mkdir(path.dirname(STATE_FILE), { recursive: true })
  await atomicWrite(STATE_FILE, JSON.stringify(state, null, 2) + '\n')
}

function dshCli(args, opts = {}) {
  // 升级链可靠性(see openspec/changes/upgrade-cli-provisioning):解析目标
  // 版本 CLI 的就绪 bin 并 node 直连执行,首次就绪后不再发起新的 npx
  // 进程,避免 libnpmexec 安装锁竞争(ECOMPROMISED)。DSH_BIN 优先保留。
  return runDshCli(args, {
    spec: `@deepseek-ai/dsh@${opts.version}`,
    version: opts.version,
    dshBinEnv: process.env.DSH_BIN,
    stdio: opts.stdio,
  })
}

/**
 * 全新 `$DSH_HOME` 的 profile 骨架物化。
 *
 * 症状:在没有 `~/.dsh` 的机器上首次 `dsh build`,syncPackages/doReset 读不到
 * `profiles/<name>/package.json` 就 fail(`profile package.json missing`),
 * 于是全部 package 定制被跳过、启动缺插件 —— sync 假定 profile 已由此前某次
 * DSH 运行初始化过,但全新机器上并没有这一前置。
 *
 * 修法:把这一前置变成 sync 自己的显式步骤,而不是复制一份 profile 模板。
 * 骨架的真相源是运行体自身(`@deepseek-ai/dsh-app-boot` 的 PROFILE_TEMPLATES /
 * initProfile:manifest + cordis.patch.yml + pnpm-workspace.yaml)。这里以
 * `--profile <name> --dump-default-config` 调用目标版本 CLI,只取其"加载
 * profile 时按需 initProfile"的副作用(不读 user layer,故不会被后续生成的
 * patch 层内容影响),输出丢弃。
 *
 * 语义:
 * - 幂等 —— manifest 已存在直接返回,不触碰任何既有文件(initProfile 本身也
 *   从不覆盖已存在的文件);
 * - fail closed —— 骨架无法物化时报错,让调用方看到真正的首因,而不是随后
 *   一连串"package 装不上"的次生失败。
 * @returns {Promise<boolean>} profile manifest 是否已就绪。
 */
async function ensureProfileScaffold(manifest) {
  const profilePkgPath = path.join(PROFILE_DIR, 'package.json')
  if (existsSync(profilePkgPath)) return true
  change(`initialize profile ${PROFILE} at ${PROFILE_DIR}`)
  await mkdir(PROFILE_DIR, { recursive: true })
  // 副作用调用:输出是整棵默认配置树,对 sync 日志无意义,丢弃。
  dshCli(['--profile', PROFILE, '--dump-default-config'], { version: manifest.dshVersion, stdio: 'ignore' })
  if (existsSync(profilePkgPath)) return true
  fail(`failed to initialize profile ${PROFILE} at ${PROFILE_DIR} (dsh ${manifest.dshVersion} could not create its profile manifest)`)
  return false
}

function npmNameOf(item) {
  if (item.source === 'local') {
    const pkg = readJson(path.join(REPO, 'packages', item.id, 'package.json'))
    if (pkg === undefined) throw new Error(`package ${item.id}: packages/${item.id}/package.json missing`)
    return pkg.name
  }
  if (item.name !== undefined) return item.name
  return parseSpec(item.spec).name
}

function installedVersion(name) {
  const pkg = readJson(path.join(PROFILE_DIR, 'node_modules', ...name.split('/'), 'package.json'))
  return pkg?.version
}

/**
 * Every runtime file a package manifest promises, as package-relative paths.
 *
 * Derived from what the loader actually resolves: `main`, the `exports` tree
 * (any nesting of condition maps / fallback arrays), and `dsh.bundle.patch`
 * (the composition patch the profile reads). Type declarations are excluded:
 * a missing `.d.ts` never breaks a running import, so demanding it would turn
 * a cosmetic gap into a redeploy.
 *
 * Conservative by construction — it must never invent a requirement:
 * - only literal relative specifiers ('./…') are collected; bare specifiers
 *   and URLs address other packages, not files here;
 * - wildcard subpaths ('./*') expand per-request and cannot be checked as a
 *   literal path, so they are skipped;
 * - `null` targets are exports *blocks*, not files;
 * - `types` / `typings` conditions are dropped (see above);
 * - a fallback *array* means "first one that resolves wins", so requiring
 *   every member would flag a healthy package; it contributes nothing;
 * - a condition map is resolved **first-match against the conditions this
 *   loader actually uses**, exactly as Node does — never unioned. Unioning
 *   would demand the `require` branch of an ESM-only package that merely
 *   declares one, condemning healthy packages (`@standard-schema/spec`,
 *   `@upsetjs/venn.js` in this very profile).
 * Anything unrecognized is ignored rather than guessed at.
 * @returns {string[]} unique package-relative paths that must exist on disk.
 */
/** Import conditions the host loader offers, in Node's resolution order. */
const RUNTIME_CONDITIONS = ['node', 'import', 'module-sync', 'default']

function declaredRuntimeFiles(pkg) {
  const found = new Set()
  const addTarget = (value) => {
    if (typeof value !== 'string') return
    if (!value.startsWith('./')) return          // bare specifier / URL: not our file
    if (value.includes('*')) return              // pattern subpath: no single literal path
    if (value.endsWith('/')) return              // directory target: not a single file
    found.add(value.replace(/^\.\//, ''))
  }
  // exports values nest arbitrarily: string | null | array of fallbacks | condition map.
  const walkExports = (node) => {
    if (node === null || node === undefined) return
    if (typeof node === 'string') return addTarget(node)
    if (Array.isArray(node)) return            // fallback list: no single member is required
    if (typeof node !== 'object') return
    // First match wins, mirroring Node — stop at the first condition this
    // runtime would select rather than requiring every branch.
    for (const condition of RUNTIME_CONDITIONS) {
      if (condition in node) return walkExports(node[condition])
    }
    // No runtime condition applies (types-only / browser-only / custom): the
    // loader never resolves this entry here, so it requires nothing.
  }
  addTarget(typeof pkg?.main === 'string' && pkg.main !== ''
    ? (pkg.main.startsWith('./') ? pkg.main : `./${pkg.main}`)
    : undefined)
  const exports = pkg?.exports
  if (typeof exports === 'string' || Array.isArray(exports)) walkExports(exports)
  else if (exports !== null && typeof exports === 'object') {
    const subpaths = Object.keys(exports).filter((key) => key.startsWith('.'))
    // Sugar form (`exports` is itself a condition map) vs. subpath map.
    if (subpaths.length === 0) walkExports(exports)
    else for (const key of subpaths) walkExports(exports[key])
  }
  addTarget(pkg?.dsh?.bundle?.patch)
  return [...found]
}

/**
 * Files a deployed package promises but does not have.
 *
 * The freshness checks around this one all reason about *metadata* — the
 * deployed `package.json`'s version, the source content hash, the recorded
 * install spec. None of them look at whether the bytes the manifest points at
 * actually arrived. An install that dies partway (the devbox trigger: a
 * `pnpm add` transaction interrupted mid-flight) leaves exactly that shape:
 * a readable `package.json` beside a missing `lib/`, which every metadata
 * check happily reads as healthy while the loader dies on `import` with
 * ERR_MODULE_NOT_FOUND.
 *
 * `./package.json` is skipped: the manifest was just parsed to get here.
 * @returns {string[]} missing package-relative paths; empty means healthy.
 */
function missingDeployedFiles(name) {
  const dir = path.join(PROFILE_DIR, 'node_modules', ...name.split('/'))
  const pkg = readJson(path.join(dir, 'package.json'))
  if (pkg === undefined) return []   // not installed at all: the version check owns that case
  // CommonJS-style tolerance: a bare `main` may address a file without its
  // extension or a directory with an index. Treat a requirement as satisfied
  // when any of those candidates exists, so legacy layouts are not condemned.
  const satisfied = (rel) => [rel, `${rel}.js`, `${rel}.mjs`, `${rel}.cjs`, `${rel}.json`, path.join(rel, 'index.js')]
    .some((candidate) => existsSync(path.join(dir, candidate)))
  return declaredRuntimeFiles(pkg)
    .filter((rel) => rel !== 'package.json' && !satisfied(rel))
}

/**
 * The spec string a remote package was installed from, as recorded in the
 * profile manifest (pnpm stores the tarball/registry URL there). Indexed by
 * package name; the entry at `name` is the one sync actually controls.
 */
function installedSpec(name) {
  const profile = readJson(path.join(PROFILE_DIR, 'package.json'))
  if (profile === undefined) return undefined
  return profile.dependencies?.[name]
}

function declaresBundle(name) {
  const pkg = readJson(path.join(PROFILE_DIR, 'node_modules', ...name.split('/'), 'package.json'))
  return pkg?.dsh?.bundle?.patch !== undefined
}

// ---------- actions ----------
function renderAgentInstructions(config, sourceContent) {
  const body = sourceContent.endsWith('\n') ? sourceContent : `${sourceContent}\n`
  return `# GENERATED by ohmydsh scripts/sync.mjs — do not edit by hand.\n# Source: ${config.source} (configured by dsh.yaml).\n\n${body}`
}

async function syncAgentInstructions(config, { reset = false } = {}) {
  const state = await loadState()
  const managed = state.agentInstructions
  const target = path.join(DSH_HOME, 'AGENTS.md')
  const targetExists = existsSync(target)

  if (reset || config === undefined || !config.enabled) {
    if (!targetExists) {
      if (managed !== undefined) {
        delete state.agentInstructions
        await saveState(state)
        change('clear stale agentInstructions state (target absent)')
      }
      return
    }
    if (managed === undefined) {
      log(`agent instructions unmanaged at ${target}; leaving in place`)
      return
    }
    const currentHash = contentHash(await readFile(target))
    if (typeof managed.deployedHash !== 'string' || currentHash !== managed.deployedHash) {
      fail(`agent instructions drift at ${target}; refusing to remove changed managed content`)
      return
    }
    change(`remove managed agent instructions ${target}`)
    await rm(target)
    delete state.agentInstructions
    await saveState(state)
    return
  }

  let sourceStat
  try {
    sourceStat = await stat(config.sourcePath)
  } catch {
    fail(`agentInstructions.source missing: ${config.source}`)
    return
  }
  if (!sourceStat.isFile()) {
    fail(`agentInstructions.source must be a file: ${config.source}`)
    return
  }

  const actualSourcePath = await realpath(config.sourcePath)
  const actualRepoPath = await realpath(REPO)
  const actualRelative = path.relative(actualRepoPath, actualSourcePath)
  if (actualRelative === '..' || actualRelative.startsWith(`..${path.sep}`) || path.isAbsolute(actualRelative)) {
    fail(`agentInstructions.source resolves outside the repository: ${config.source}`)
    return
  }

  const desired = renderAgentInstructions(config, await readFile(actualSourcePath, 'utf8'))
  const desiredHash = contentHash(desired)
  if (targetExists) {
    const currentHash = contentHash(await readFile(target))
    if (managed === undefined) {
      if (currentHash !== desiredHash) {
        fail(`agent instructions target is unmanaged at ${target}; refusing to overwrite existing content`)
        return
      }
      change(`adopt matching agent instructions ${target}`)
    } else {
      if (typeof managed.deployedHash !== 'string' || currentHash !== managed.deployedHash) {
        fail(`agent instructions drift at ${target}; refusing to overwrite changed managed content`)
        return
      }
      if (currentHash === desiredHash) {
        log('agent instructions up-to-date')
        return
      }
      change(`update agent instructions ${target}`)
      await atomicWrite(target, desired)
    }
  } else {
    if (managed !== undefined) {
      delete state.agentInstructions
      await saveState(state)
      log('cleared stale agentInstructions state before deployment')
    }
    change(`generate agent instructions ${target}`)
    await atomicWrite(target, desired)
  }

  state.agentInstructions = { source: config.source, deployedHash: desiredHash }
  await saveState(state)
}

/**
 * Bundle-less support packages from the top-level `dependencies` list:
 * install / pin / remove as plain profile dependencies. Never join the
 * bundle layer stack (`dsh plugin add` reconciliation already keeps
 * bundle-less packages out); state tracking mirrors managedPackages.
 */
async function syncDependencies(manifest) {
  const state = await loadState()
  const currentNames = new Set(manifest.deps.map((d) => d.name))
  const previousNames = state.managedDependencies ?? []
  for (const name of previousNames) {
    if (currentNames.has(name)) continue
    if (installedVersion(name) !== undefined) {
      change(`remove dependency ${name}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove dependency ${name}`)
    }
  }
  for (const dep of manifest.deps) {
    const current = installedVersion(dep.name)
    if (current !== undefined && current !== dep.version) {
      change(`dependency drift ${dep.name} ${current} -> ${dep.version}, re-adding`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', `${dep.name}@${dep.version}`], { version: manifest.dshVersion })) fail(`failed to pin dependency ${dep.name}`)
    } else if (current === undefined) {
      change(`install dependency ${dep.name} (${dep.spec})`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', dep.spec], { version: manifest.dshVersion })) fail(`failed to install dependency ${dep.name}`)
    } else {
      log(`dependency ${dep.name}@${current} up-to-date`)
    }
  }
  state.managedDependencies = [...currentNames]
  await saveState(state)
}

async function syncPackages(manifest, items) {
  const packages = items.filter((i) => i.type === 'package')
  const enabled = packages.filter((i) => i.enabled)
  const profilePkgPath = path.join(PROFILE_DIR, 'package.json')
  const profilePkg = readJson(profilePkgPath)
  if (profilePkg === undefined) return fail(`profile package.json missing at ${PROFILE_DIR}`)

  const names = new Map()
  for (const item of packages) {
    try { names.set(item.id, npmNameOf(item)) } catch (e) { fail(String(e.message ?? e)) }
  }
  const enabledNames = enabled.map((i) => names.get(i.id)).filter(Boolean)
  const state = await loadState()
  const previousCompatByOwner = state.managedCompatDependencies ?? {}
  const compatByOwner = new Map()
  const claimedCompatNames = new Set()
  for (const item of packages) {
    const owner = names.get(item.id)
    if (owner === undefined) continue
    const entries = item.compatDependencies ?? []
    for (const entry of entries) {
      if (claimedCompatNames.has(entry.name) || [...names.values()].includes(entry.name)) {
        fail(`local package ${owner}: compatibility dependency name ${entry.name} is not uniquely owned`)
        continue
      }
      claimedCompatNames.add(entry.name)
    }
    compatByOwner.set(owner, entries)
  }

  // Local package specs embed the absolute checkout path. Repair stale paths
  // before any plugin command so a moved/renamed repository cannot make pnpm
  // fail while reconciling an otherwise unrelated package.
  let repairedLocalSpecs = false
  profilePkg.dependencies ??= {}
  for (const item of enabled.filter((entry) => entry.source === 'local')) {
    const name = names.get(item.id)
    const expected = `file:${path.join(REPO, 'packages', item.id)}`
    if (name !== undefined && profilePkg.dependencies[name] !== expected) {
      change(`local package path ${name} -> ${expected}`)
      profilePkg.dependencies[name] = expected
      repairedLocalSpecs = true
    }
  }
  if (repairedLocalSpecs) await writeJson(profilePkgPath, profilePkg)

  // Remove a disabled owner and every compatibility override it owns in one
  // pnpm transaction. This restores DSH's install-anchor fallback without a
  // window where the bundle is active against the wrong Connection package.
  for (const [id, name] of names) {
    const item = packages.find((i) => i.id === id)
    if (item.enabled) continue
    const compatNames = [...new Set([
      ...(compatByOwner.get(name) ?? []).map(entry => entry.name),
      ...(previousCompatByOwner[name] ?? []),
    ])]
    const removal = [name, ...compatNames].filter(packageName =>
      profilePkg.dependencies?.[packageName] !== undefined || installedVersion(packageName) !== undefined)
    if (removal.length > 0) {
      change(`remove disabled package ${name}${compatNames.length > 0 ? ' with compatibility overrides' : ''}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', ...removal], { version: manifest.dshVersion })) {
        fail(`failed to remove ${removal.join(', ')}`)
      } else {
        delete previousCompatByOwner[name]
      }
    } else {
      delete previousCompatByOwner[name]
    }
  }

  // remove entries deleted from the manifest (previously managed, now absent);
  // names now managed as top-level dependencies are not ours to remove
  const depNames = new Set(manifest.deps.map((d) => d.name))
  const currentNames = new Set(names.values())
  const previousNames = state.managedPackages ?? []
  for (const name of previousNames) {
    if (currentNames.has(name) || depNames.has(name)) continue
    const compatNames = previousCompatByOwner[name] ?? []
    const removal = [name, ...compatNames].filter(packageName =>
      profilePkg.dependencies?.[packageName] !== undefined || installedVersion(packageName) !== undefined)
    if (removal.length > 0) {
      change(`remove deleted package ${name}${compatNames.length > 0 ? ' with compatibility overrides' : ''}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', ...removal], { version: manifest.dshVersion })) {
        fail(`failed to remove ${removal.join(', ')}`)
      } else {
        delete previousCompatByOwner[name]
      }
    } else {
      delete previousCompatByOwner[name]
    }
  }
  state.managedPackages = [...currentNames]
  await saveState(state)

  // Local file dependencies are copied into the profile rather than symlinked.
  // Build from source before any remove/reinstall, then compare only publishable
  // bytes. Build-input and install-content identities are deliberately separate.
  const previousLocalHashes = state.localPackageHashes ?? {}
  const previousBuildInputs = state.localPackageBuildInputs ?? {}
  const previousCompatHashes = state.compatDependencyHashes ?? {}
  // Packages proven incomplete at their source, keyed by the identity that was
  // proven bad (local content hash / remote spec). Keeping the identity means a
  // new version or a fixed tarball is retried automatically.
  const previousUnrepairable = state.unrepairablePackages ?? {}
  const nextUnrepairable = {}
  const enabledNameSet = new Set(enabledNames)
  // Preserve the last successful ledger for enabled owners across a failed
  // rebuild. Their deployed profile bytes remain intact, so erasing these
  // hashes would cause a needless replacement after the fixed input is restored.
  const nextLocalHashes = Object.fromEntries(Object.entries(previousLocalHashes)
    .filter(([packageName]) => enabledNameSet.has(packageName)))
  const nextBuildInputs = Object.fromEntries(Object.entries(previousBuildInputs)
    .filter(([packageName]) => enabledNameSet.has(packageName)))
  const enabledCompatNames = new Set(enabled.flatMap(item =>
    (item.compatDependencies ?? []).map(entry => entry.name)))
  const nextCompatHashes = Object.fromEntries(Object.entries(previousCompatHashes)
    .filter(([packageName]) => enabledCompatNames.has(packageName)))
  const nextManagedCompat = Object.fromEntries(Object.entries(previousCompatByOwner)
    .filter(([packageName]) => enabledNameSet.has(packageName)))
  for (const item of enabled) {
    const name = names.get(item.id)
    const localDir = item.source === 'local' ? path.join(REPO, 'packages', item.id) : undefined
    const currentCompatNames = (compatByOwner.get(name) ?? []).map(entry => entry.name)
    const removedCompatNames = (previousCompatByOwner[name] ?? [])
      .filter(packageName => !currentCompatNames.includes(packageName))
    if (removedCompatNames.length > 0) {
      fail(`local package ${name}: refusing to remove or rename active compatibility overrides (${removedCompatNames.join(', ')}); disable the owner and sync first`)
      continue
    }
    const spec = localDir === undefined ? item.spec : `file:${localDir}`
    let localHash
    let buildInputHash
    if (localDir !== undefined) {
      const localPkg = readJson(path.join(localDir, 'package.json'))
      buildInputHash = await localBuildInputHash(localDir, item.buildInputs ?? [])
      const needsBuild = typeof localPkg?.scripts?.build === 'string' && (
        previousBuildInputs[name] !== buildInputHash || !localBuildOutputsExist(localDir, localPkg)
      )
      if (needsBuild && !runLocalBuild(item, localDir)) continue
      if (!localBuildOutputsExist(localDir, localPkg)) {
        fail(`local package ${name}: build outputs are missing after build readiness check`)
        continue
      }
      localHash = await localInstallContentHash(localDir)
    }
    const compatEntries = localDir === undefined ? [] : (compatByOwner.get(name) ?? [])
    const compatSpecs = []
    const compatHashes = {}
    let compatInvalid = false
    for (const entry of compatEntries) {
      const compatDir = path.join(localDir, entry.path)
      const compatPkg = readJson(path.join(compatDir, 'package.json'))
      if (compatPkg?.name !== entry.name) {
        fail(`local package ${name}: compatibility artifact ${entry.path} must declare name ${entry.name}`)
        compatInvalid = true
        break
      }
      compatSpecs.push(`file:${compatDir}`)
      compatHashes[entry.name] = await dirHash(compatDir)
    }
    if (compatInvalid) continue

    const current = installedVersion(name)
    const currentlyInstalledFrom = installedSpec(name)
    // A remoted pin change must trigger re-install even when the package version
    // is unchanged: bumping the spec commit is exactly how a fork patch update
    // deploys, and sync previously only compared version. Only tarball/URL specs
    // are compared this way: pnpm stores a plain version for registry specs
    // (`name@version` is normalized away), so comparing those here would falsely
    // drift every registry package. Registry drift stays covered by the version
    // compare below.
    const pinSpec = typeof item.spec === 'string'
      && typeof item.name === 'string'
      && (/^(?:https?:|git\+|file:)/.test(item.spec) || /\.(?:tar\.gz|tgz)($|\?)/.test(item.spec))
    const pinDrift = item.source === 'remote'
      && current !== undefined
      && pinSpec
      && currentlyInstalledFrom !== undefined
      && currentlyInstalledFrom !== item.spec
    const compatChanged = compatEntries.some(entry =>
      installedVersion(entry.name) === undefined || previousCompatHashes[entry.name] !== compatHashes[entry.name])
    // Deployment-side integrity. Every other trigger here compares metadata
    // (version / source hash / recorded spec) and so cannot see a package that
    // is installed but incomplete. Checked for local and remote alike: an
    // interrupted install truncates either one the same way.
    const missingFiles = current === undefined ? [] : missingDeployedFiles(name)
    // A package whose *source* cannot satisfy its own manifest (an incomplete
    // published tarball, e.g. the dsh-cockpit-bridge@0.1.0 incident recorded in
    // dsh.yaml) is unrepairable by reinstalling. Once proven so for this exact
    // identity, report it and stop: re-running the install every sync would
    // churn a network fetch forever without ever converging.
    // Identity of what was proven incomplete. Must be stable across runs, so it
    // is derived from the manifest (source hash / declared spec+version) rather
    // than from the deployed state, which differs between the first install and
    // later runs. A new version or a re-published tarball changes it and the
    // package is retried automatically.
    const repairIdentity = item.source === 'local' ? `local:${localHash}` : `remote:${item.spec}@${item.version}`
    let installed = true
    if (missingFiles.length > 0 && previousUnrepairable[name] === repairIdentity) {
      fail(`${name} is incomplete at its source and cannot be repaired by reinstalling (missing ${missingFiles.join(', ')}); pin a fixed version or disable it`)
      nextUnrepairable[name] = repairIdentity
      installed = false
    } else if (missingFiles.length > 0) {
      change(`incomplete deployment ${name}: missing ${missingFiles.join(', ')}, reinstalling`)
      // Two stages, ordered so a failure can never destroy a working deployment.
      // Stage 1 is a plain re-add: cheap, transactional, and enough whenever the
      // package manager will re-materialize the tree.
      installed = dshCli(['plugin', '--profile', PROFILE, 'add', ...compatSpecs, spec], { version: manifest.dshVersion })
      if (!installed) {
        fail(`failed to repair incomplete deployment of ${name}`)
      } else if (missingDeployedFiles(name).length > 0) {
        // Stage 2. pnpm keys a `file:` dependency on the source directory's
        // identity, so with the manifest already satisfied it re-links the same
        // truncated tree and stage 1 changes nothing. Evicting the deployed copy
        // forces a fresh materialization — but only now that stage 1 has proven
        // the install itself succeeds, so this cannot strand a package that was
        // merely degraded. Restore the evicted tree if the retry fails.
        const deployedDir = path.join(PROFILE_DIR, 'node_modules', ...name.split('/'))
        const quarantine = `${deployedDir}.ohmydsh-recovering`
        await rm(quarantine, { recursive: true, force: true })
        await rename(deployedDir, quarantine).catch(() => {})
        installed = dshCli(['plugin', '--profile', PROFILE, 'add', ...compatSpecs, spec], { version: manifest.dshVersion })
        const stillMissing = installed ? missingDeployedFiles(name) : []
        if (!installed || stillMissing.length > 0) {
          if (!existsSync(deployedDir) && existsSync(quarantine)) {
            await rename(quarantine, deployedDir).catch(() => {})
            log(`restored previous deployment of ${name} after failed repair`)
          }
          installed = false
          // Remember the identity so the next run reports instead of retrying.
          nextUnrepairable[name] = repairIdentity
          fail(stillMissing.length > 0
            ? `deployment of ${name} still missing after reinstall: ${stillMissing.join(', ')}`
            : `failed to repair incomplete deployment of ${name}`)
        }
        await rm(quarantine, { recursive: true, force: true })
      }
    } else if (pinDrift) {
      change(`spec drift ${name} ${currentlyInstalledFrom} -> ${item.spec}, re-adding`)
      installed = dshCli(['plugin', '--profile', PROFILE, 'add', item.spec], { version: manifest.dshVersion })
    } else if (current !== undefined && item.source === 'remote' && current !== item.version) {
      change(`version drift ${name} ${current} -> ${item.version}, re-adding`)
      installed = dshCli(['plugin', '--profile', PROFILE, 'add', item.spec], { version: manifest.dshVersion })
      if (!installed) fail(`failed to pin ${name}`)
    } else if (item.source === 'local' && (
      current === undefined || current !== item.version || previousLocalHashes[name] !== localHash || compatChanged
    )) {
      if (current === undefined) {
        change(`install local package ${name} (${spec})`)
        installed = dshCli(['plugin', '--profile', PROFILE, 'add', ...compatSpecs, spec], { version: manifest.dshVersion })
        if (!installed) fail(`failed to install ${name}`)
      } else if (previousLocalHashes[name] !== localHash && !compatChanged) {
        // Content drift. pnpm `file:` directory dependencies merge without
        // overwriting existing subtree files, so a plain re-add may leave the
        // deployed copy stale while the source-side hash says "current".
        // Verify the DEPLOYED bytes: already matching means the drift was
        // deployed by other means (manual refresh, previous repair) — record
        // the hash and move on; mismatching forces an atomic refresh.
        const deployedHash = await deployedContentHash(readJson(path.join(localDir, 'package.json')), name)
        if (deployedHash === localHash) {
          log(`package ${name}@${current} content changed, deployment already matches source`)
          installed = true
        } else {
          change(`local package ${name} content changed, reinstalling atomically`)
          // Evict-then-add so the deployed copy cannot keep stale subtree
          // files; refresh re-verifies and restores the old copy on failure.
          installed = await refreshLocalDeployment(localDir, name, spec, compatSpecs, localHash, manifest.dshVersion)
          if (!installed) fail(`failed to refresh deployment of ${name}`)
        }
      } else {
        // Version pin drift or a compatibility artifact change: same install
        // mechanics as before (the atomic refresh path above owns content).
        const reason = current !== item.version ? `${current} -> ${item.version}` : 'compatibility artifact changed'
        const action = `local package ${name} ${reason}, reinstalling atomically`
        change(`${action}${compatEntries.length > 0 ? ' with compatibility overrides' : ''}`)
        // pnpm stages and commits all local specs as one operation. Do not remove
        // the last-known-good owner first: a failed build or add must leave the
        // previous federation + Connection pair intact.
        installed = dshCli(['plugin', '--profile', PROFILE, 'add', ...compatSpecs, spec], { version: manifest.dshVersion })
        if (!installed) fail(`failed to deploy ${name}${compatEntries.length > 0 ? ' and compatibility overrides' : ''}`)
      }
    } else if (current === undefined) {
      change(`install ${item.source} package ${name} (${spec})`)
      installed = dshCli(['plugin', '--profile', PROFILE, 'add', spec], { version: manifest.dshVersion })
      if (!installed) fail(`failed to install ${name}`)
    } else {
      log(`package ${name}@${current} up-to-date`)
    }
    // Post-install verification for every path above, not just the repair
    // branch: the CLI's exit code reports that the install *ran*, never that
    // the promised files arrived. A first install of an incomplete publish
    // would otherwise be recorded as a success and only surface later as a
    // loader crash. Skipped when the install already failed (that failure is
    // the first cause and is reported on its own).
    if (installed && missingFiles.length === 0) {
      const missingAfterInstall = missingDeployedFiles(name)
      if (missingAfterInstall.length > 0) {
        installed = false
        nextUnrepairable[name] = repairIdentity
        fail(`${name} installed but is missing ${missingAfterInstall.join(', ')}; its source does not satisfy its own manifest`)
      }
    }
    if (installed && localHash !== undefined && buildInputHash !== undefined) {
      nextLocalHashes[name] = localHash
      nextBuildInputs[name] = buildInputHash
      Object.assign(nextCompatHashes, compatHashes)
      nextManagedCompat[name] = compatEntries.map(entry => entry.name)
    }
  }
  state.localPackageHashes = nextLocalHashes
  state.localPackageBuildInputs = nextBuildInputs
  state.compatDependencyHashes = nextCompatHashes
  state.managedCompatDependencies = nextManagedCompat
  // Rebuilt from scratch each run: a package that no longer reports missing
  // files simply stops being listed, so a fixed upstream self-clears.
  if (Object.keys(nextUnrepairable).length > 0) state.unrepairablePackages = nextUnrepairable
  else delete state.unrepairablePackages
  await saveState(state)

  // normalize bundles: shipped base (non-managed) entries first, then enabled managed in manifest order.
  // Only bundle-declaring packages join the layer stack: a package without a dsh.bundle manifest
  // is a plain dependency (mirrors `dsh plugin add` reconciliation); forcing it into bundles
  // would fail profile load ("bundle without dsh.bundle manifest").
  const refreshed = readJson(profilePkgPath)
  if (refreshed !== undefined) {
    const managed = new Set([...names.values(), ...(state.managedPackages ?? [])])
    const base = (refreshed.dsh?.profile?.bundles ?? []).filter((b) => !managed.has(b))
    const bundleNames = enabledNames.filter((name) => declaresBundle(name))
    const bundles = [...base, ...bundleNames]
    const before = JSON.stringify(refreshed.dsh?.profile?.bundles ?? [])
    refreshed.dsh ??= {}
    refreshed.dsh.profile ??= {}
    refreshed.dsh.profile.bundles = bundles
    if (JSON.stringify(bundles) !== before) {
      change(`bundles: [${bundles.join(', ')}]`)
      await writeJson(profilePkgPath, refreshed)
    }
    if (JSON.stringify(state.shippedBundles ?? []) !== JSON.stringify(base)) {
      state.shippedBundles = base
      await saveState(state)
    }
  }
}

/**
 * One-click reset: remove every plugin beyond the shipped base set, reset the
 * generated patch layer, and drop synced presets/skills. Reversible via sync.
 */
async function doReset(manifest) {
  const state = await loadState()
  const shipped = state.shippedBundles ?? ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app']
  const profilePkgPath = path.join(PROFILE_DIR, 'package.json')
  const profilePkg = readJson(profilePkgPath)
  if (profilePkg === undefined) return fail(`profile package.json missing at ${PROFILE_DIR}`)

  const bundles = profilePkg.dsh?.profile?.bundles ?? []
  const removable = [...new Set([
    ...bundles.filter((b) => !shipped.includes(b)),
    ...Object.keys(profilePkg.dependencies ?? {}).filter((d) => !shipped.includes(d)),
  ])]
  for (const name of removable) {
    change(`remove plugin ${name}`)
    if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove ${name}`)
  }

  const refreshed = readJson(profilePkgPath) ?? profilePkg
  refreshed.dsh ??= {}
  refreshed.dsh.profile ??= {}
  refreshed.dsh.profile.bundles = shipped
  await writeJson(profilePkgPath, refreshed)

  const target = path.join(PROFILE_DIR, 'cordis.patch.yml')
  const content = GENERATED_HEADER + '\n[]\n'
  if (!existsSync(target) || readFileSync(target, 'utf8') !== content) {
    if (existsSync(target)) await writeFile(target + '.bak', readFileSync(target, 'utf8'))
    change(`reset ${target}`)
    await mkdir(path.dirname(target), { recursive: true })
    await writeFile(target, content)
  }

  for (const key of Object.keys(state)) {
    const m = key.match(/^(preset|skill):(.+)$/)
    if (m === null) continue
    const dst = path.join(DSH_HOME, m[1] === 'preset' ? '.agent-presets' : 'skills', m[2])
    if (existsSync(dst)) {
      change(`remove ${m[1]} ${m[2]}`)
      await rm(dst, { recursive: true, force: true })
    }
    delete state[key]
  }
  delete state.managedPackages
  delete state.localPackageHashes
  delete state.localPackageBuildInputs
  delete state.compatDependencyHashes
  delete state.managedCompatDependencies
  delete state.managedDependencies
  delete state['managed:preset']
  delete state['managed:skill']
  await saveState(state)
}

async function syncDirs(manifest, items, type, srcDir, dstRoot, requiredFile, label) {
  const state = await loadState()
  const managed = items.filter((i) => i.type === type)
  const enabled = managed.filter((i) => i.enabled)
  for (const item of enabled) {
    const src = path.join(REPO, srcDir, item.id)
    const dst = path.join(dstRoot, item.id)
    if (!existsSync(path.join(src, requiredFile))) {
      fail(`${label} ${item.id}: ${path.join(srcDir, item.id)}/${requiredFile} missing`)
      continue
    }
    const hash = await dirHash(src)
    if (state[`${type}:${item.id}`] === hash && existsSync(path.join(dst, requiredFile))) {
      log(`${label} ${item.id} up-to-date`)
      continue
    }
    change(`copy ${label} ${item.id} -> ${dst}`)
    await rm(dst, { recursive: true, force: true })
    await mkdir(path.dirname(dst), { recursive: true })
    await cp(src, dst, { recursive: true })
    state[`${type}:${item.id}`] = hash
  }
  for (const item of managed.filter((i) => !i.enabled)) {
    const key = `${type}:${item.id}`
    if (state[key] !== undefined) {
      const dst = path.join(dstRoot, item.id)
      if (existsSync(dst)) {
        change(`remove disabled ${label} ${item.id}`)
        await rm(dst, { recursive: true, force: true })
      }
      delete state[key]
    }
  }
  // remove entries deleted from the manifest (previously managed, now absent)
  const currentIds = new Set(managed.map((i) => i.id))
  for (const id of state[`managed:${type}`] ?? []) {
    if (currentIds.has(id)) continue
    const key = `${type}:${id}`
    if (state[key] !== undefined) {
      const dst = path.join(dstRoot, id)
      if (existsSync(dst)) {
        change(`remove deleted ${label} ${id}`)
        await rm(dst, { recursive: true, force: true })
      }
    }
    delete state[key]
  }
  state[`managed:${type}`] = [...currentIds]
  await saveState(state)
}

async function syncPatches(items, manifest) {
  const fragments = items.filter((i) => i.type === 'patch' && i.enabled)
  const target = path.join(PROFILE_DIR, 'cordis.patch.yml')
  const parts = []
  for (const item of fragments) {
    const file = path.join(REPO, 'patches', `${item.id}.yml`)
    if (!existsSync(file)) {
      fail(`patch ${item.id}: patches/${item.id}.yml missing`)
      continue
    }
    parts.push(`# --- fragment: ${item.id} ---\n` + readFileSync(file, 'utf8').trimEnd() + '\n')
  }
  const body = parts.length === 0 ? '[]\n' : parts.join('\n')
  const content = GENERATED_HEADER + '\n' + body
  const existing = existsSync(target) ? readFileSync(target, 'utf8') : ''
  if (existing === content) {
    log('patches up-to-date')
    return
  }
  change(`generate ${target}`)
  if (existing !== '') await writeFile(target + '.bak', existing)
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, content)
}

function logVersion(manifest) {
  log(`dshVersion: ${manifest.dshVersion} (launcher bin/dsh reads dsh.yaml as the single source)`)
}

// ---------- main ----------
async function main() {
  const manifest = loadManifest()
  await mkdir(PROFILE_DIR, { recursive: true })
  await migrateLegacyState()
  // 全新机器上 profile 骨架尚不存在;package 物化与 reset 都以它为前置。
  await ensureProfileScaffold(manifest)
  if (process.argv.includes('--reset')) {
    await doReset(manifest)
    await syncAgentInstructions(manifest.agentInstructions, { reset: true })
  } else {
    await syncAgentInstructions(manifest.agentInstructions)
    await syncDependencies(manifest)
    await syncPackages(manifest, manifest.items)
    await syncDirs(manifest, manifest.items, 'preset', 'presets', path.join(DSH_HOME, '.agent-presets'), 'agent.cordis.yml', 'preset')
    await syncDirs(manifest, manifest.items, 'skill', 'skills', path.join(DSH_HOME, 'skills'), 'SKILL.md', 'skill')
    await syncPatches(manifest.items, manifest)
  }
  logVersion(manifest)
  console.log('')
  if (failures.length > 0) {
    console.error(`[sync] finished with ${failures.length} failure(s):`)
    for (const f of failures) console.error(`  - ${f}`)
    process.exitCode = 1
    return
  }
  if (changes.length === 0) log('no changes — deployment already matches manifest')
  else log(`done — ${changes.length} change(s) applied`)
}

main().catch((error) => {
  console.error(`[sync] ERROR ${String(error?.message ?? error)}`)
  process.exitCode = 1
})
