#!/usr/bin/env node
// ohmydsh sync — materialize dsh.yaml customizations into ~/.dsh.
// Idempotent; the repository (dsh.yaml + customization dirs) is the source of truth.
import { readFile, writeFile, mkdir, cp, rm, readdir, stat, rename, realpath } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import path from 'node:path'
import os from 'node:os'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DSH_HOME = resolveDshHome(process.env.DSH_HOME)
const PROFILE = process.env.DSH_PROFILE ?? 'web'
const PROFILE_DIR = path.join(DSH_HOME, 'profiles', PROFILE)
const STATE_FILE = path.join(DSH_HOME, '.ohmydsh-sync-state.json')
const GENERATED_HEADER = `# GENERATED by ohmydsh scripts/sync.mjs — do not edit by hand.\n# Source of truth: ${REPO}/dsh.yaml and patches/. Edit there, then re-run sync.\n`

/** Truthy/falsy spellings accepted for the DSH_LAN env override. */
const LAN_TRUE = new Set(['1', 'true', 'yes', 'on'])
const LAN_FALSE = new Set(['0', 'false', 'no', 'off'])
/** Generated patch fragment when LAN serving is on: bind the webserver to all interfaces. */
const LAN_FRAGMENT = `# --- fragment: web-lan (generated from manifest web.lan / DSH_LAN) ---
# Bind the webserver to all interfaces: the Web GUI and the full agent surface
# are reachable from the LAN. dsh-web-app derives the LAN IP literals from the
# bind and feeds the browser-trust fence; the launcher prints the LAN URL.
# Launch with --host 127.0.0.1 to force loopback-only for that run.
- id: webserver
  config:
    host: !!js ctx.webStartup.host ?? '0.0.0.0'
    port: !!js ctx.webStartup.port ?? 3080
`

/**
 * Resolve the LAN serving switch. An explicit DSH_LAN env value (inline or
 * from .env.local) beats the manifest; unset or unrecognized falls back to
 * manifest web.lan (default off).
 */
function resolveWebLan(manifest) {
  const raw = process.env.DSH_LAN
  if (raw !== undefined && raw.trim() !== '') {
    const v = raw.trim().toLowerCase()
    if (LAN_TRUE.has(v)) return true
    if (LAN_FALSE.has(v)) return false
  }
  return manifest.web.lan
}

const failures = []
const changes = []
const log = (msg) => console.log(`[sync] ${msg}`)
const change = (msg) => { changes.push(msg); log(msg) }
const fail = (msg) => { failures.push(msg); console.error(`[sync] ERROR ${msg}`) }

// ---------- manifest ----------
function loadManifest() {
  const file = path.join(REPO, 'dsh.yaml')
  if (!existsSync(file)) {
    throw new Error(`manifest missing: ${file} — create it first (see README.md)`)
  }
  const doc = yaml.load(readFileSync(file, 'utf8'))
  if (typeof doc !== 'object' || doc === null) throw new Error(`manifest ${file} is empty or not a YAML mapping`)
  if (typeof doc.dshVersion !== 'string' || doc.dshVersion === '') throw new Error('manifest: dshVersion is required')
  if (!Array.isArray(doc.customizations)) throw new Error('manifest: customizations must be a list')

  // top-level dependencies: bundle-less support packages (exact-version npm specs)
  const deps = (doc.dependencies ?? []).map((spec, index) => {
    const label = `dependencies[${index}]`
    if (typeof spec !== 'string') throw new Error(`${label}: must be a string npm spec with exact version`)
    const parsed = parseSpec(spec)
    if (parsed === undefined) throw new Error(`${label}: "${spec}" — expected "<name>@<version>"`)
    return { ...parsed, spec }
  })
  const depNames = new Set(deps.map((d) => d.name))

  const items = doc.customizations.map((item, index) => {
    const label = `customizations[${index}]`
    if (typeof item.id !== 'string' || !/^[a-z0-9][a-z0-9._-]*$/i.test(item.id)) throw new Error(`${label}: valid string id required`)
    if (!['package', 'preset', 'patch', 'skill'].includes(item.type)) throw new Error(`${label} (${item.id}): type must be package|preset|patch|skill`)
    const source = item.source ?? 'local'
    if (!['local', 'remote'].includes(source)) throw new Error(`${label} (${item.id}): source must be local|remote`)
    if (source === 'remote' && item.type !== 'package') throw new Error(`${label} (${item.id}): source remote only applies to type package`)
    if (item.type === 'package' && source === 'remote' && typeof item.spec !== 'string') throw new Error(`${label} (${item.id}): remote package requires spec`)
    if (item.name !== undefined && (typeof item.name !== 'string' || !/^(@[^/@]+\/[^/@]+|[^/@]+)$/.test(item.name))) throw new Error(`${label} (${item.id}): name must be a valid npm package name`)
    if (item.type === 'package' && source === 'remote' && parseSpec(item.spec) === undefined && item.name === undefined) throw new Error(`${label} (${item.id}): remote package with a non-npm spec requires an explicit name (real npm package name)`)
    if ((item.type === 'package' || item.type === 'preset') && typeof item.version !== 'string') throw new Error(`${label} (${item.id}): package/preset requires version`)
    // deps: ownership references into the top-level dependencies list (not an install source)
    if (item.deps !== undefined) {
      if (!Array.isArray(item.deps) || item.deps.some((d) => typeof d !== 'string')) throw new Error(`${label} (${item.id}): deps must be a list of package names`)
      for (const name of item.deps) {
        if (!depNames.has(name)) throw new Error(`${label} (${item.id}): deps references "${name}" which is missing from top-level dependencies`)
      }
    }
    return { ...item, source, enabled: item.enabled !== false }
  })
  const web = doc.web ?? {}
  if (typeof web !== 'object' || web === null || Array.isArray(web)) {
    throw new Error('manifest: web must be a mapping (web.lan: true|false)')
  }
  if (web.lan !== undefined && typeof web.lan !== 'boolean') {
    throw new Error('manifest: web.lan must be a boolean')
  }
  const agentInstructions = validateAgentInstructions(doc.agentInstructions)
  return { dshVersion: doc.dshVersion, items, deps, agentInstructions, web: { lan: web.lan === true } }
}

function validateAgentInstructions(value) {
  if (value === undefined) return undefined
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('manifest: agentInstructions must be a mapping with enabled and source')
  }
  if (typeof value.enabled !== 'boolean') throw new Error('manifest: agentInstructions.enabled must be a boolean')
  if (typeof value.source !== 'string' || value.source.trim() === '') {
    throw new Error('manifest: agentInstructions.source must be a non-empty repository-relative path')
  }
  const source = value.source.trim()
  if (path.isAbsolute(source)) throw new Error('manifest: agentInstructions.source must be a repository-relative path, not an absolute path')
  const sourcePath = path.resolve(REPO, source)
  const relative = path.relative(REPO, sourcePath)
  if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error('manifest: agentInstructions.source must not escape the repository')
  }
  return { enabled: value.enabled, source: relative.split(path.sep).join('/'), sourcePath }
}

function parseSpec(spec) {
  const m = String(spec).match(/^(@[^/@]+\/[^/@]+|[^/@]+)@(.+)$/)
  if (m === null || m[2] === '') return undefined
  return { name: m[1], version: m[2] }
}

// ---------- helpers ----------
function resolveDshHome(value) {
  const configured = typeof value === 'string' ? value.trim() : ''
  if (configured === '') return path.join(os.homedir(), '.dsh')
  if (configured === '~') return os.homedir()
  if (configured.startsWith(`~${path.sep}`) || configured.startsWith('~/')) {
    return path.resolve(os.homedir(), configured.slice(2))
  }
  return path.resolve(configured)
}

function readJson(file) {
  try { return JSON.parse(readFileSync(file, 'utf8')) } catch { return undefined }
}

async function writeJson(file, value) {
  await writeFile(file, JSON.stringify(value, null, 2) + '\n')
}

function contentHash(content) {
  return createHash('sha256').update(content).digest('hex')
}

async function atomicWrite(file, content) {
  await mkdir(path.dirname(file), { recursive: true })
  const temp = path.join(path.dirname(file), `.${path.basename(file)}.tmp-${process.pid}-${Date.now()}`)
  try {
    await writeFile(temp, content, { flag: 'wx' })
    await rename(temp, file)
  } finally {
    await rm(temp, { force: true })
  }
}

async function dirHash(dir) {
  const entries = await collectFiles(dir)
  const h = createHash('sha256')
  for (const rel of entries.sort()) {
    h.update(rel + '\0')
    h.update(await readFile(path.join(dir, rel)))
  }
  return h.digest('hex')
}

async function collectFiles(dir, base = dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await collectFiles(full, base))
    else if (entry.isFile()) out.push(path.relative(base, full))
  }
  return out
}

async function loadState() {
  return readJson(STATE_FILE) ?? {}
}

async function saveState(state) {
  await mkdir(path.dirname(STATE_FILE), { recursive: true })
  await atomicWrite(STATE_FILE, JSON.stringify(state, null, 2) + '\n')
}

function dshCli(args, opts = {}) {
  const base = process.env.DSH_BIN
    ? [process.env.DSH_BIN]
    : ['npx', '-y', `@deepseek-ai/dsh@${opts.version}`]
  const r = spawnSync(base[0], [...base.slice(1), ...args], { stdio: 'inherit' })
  return r.status === 0
}

function npmNameOf(item) {
  if (item.source === 'local') {
    const pkg = readJson(path.join(REPO, 'packages', item.id, 'package.json'))
    if (pkg === undefined) throw new Error(`package ${item.id}: packages/${item.id}/package.json missing`)
    return pkg.name
  }
  if (item.name !== undefined) return item.name
  return parseSpec(item.spec).name
}

function installedVersion(name) {
  const pkg = readJson(path.join(PROFILE_DIR, 'node_modules', ...name.split('/'), 'package.json'))
  return pkg?.version
}

function declaresBundle(name) {
  const pkg = readJson(path.join(PROFILE_DIR, 'node_modules', ...name.split('/'), 'package.json'))
  return pkg?.dsh?.bundle?.patch !== undefined
}

// ---------- actions ----------
function renderAgentInstructions(config, sourceContent) {
  const body = sourceContent.endsWith('\n') ? sourceContent : `${sourceContent}\n`
  return `# GENERATED by ohmydsh scripts/sync.mjs — do not edit by hand.\n# Source: ${config.source} (configured by dsh.yaml).\n\n${body}`
}

async function syncAgentInstructions(config, { reset = false } = {}) {
  const state = await loadState()
  const managed = state.agentInstructions
  const target = path.join(DSH_HOME, 'AGENTS.md')
  const targetExists = existsSync(target)

  if (reset || config === undefined || !config.enabled) {
    if (!targetExists) {
      if (managed !== undefined) {
        delete state.agentInstructions
        await saveState(state)
        change('clear stale agentInstructions state (target absent)')
      }
      return
    }
    if (managed === undefined) {
      log(`agent instructions unmanaged at ${target}; leaving in place`)
      return
    }
    const currentHash = contentHash(await readFile(target))
    if (typeof managed.deployedHash !== 'string' || currentHash !== managed.deployedHash) {
      fail(`agent instructions drift at ${target}; refusing to remove changed managed content`)
      return
    }
    change(`remove managed agent instructions ${target}`)
    await rm(target)
    delete state.agentInstructions
    await saveState(state)
    return
  }

  let sourceStat
  try {
    sourceStat = await stat(config.sourcePath)
  } catch {
    fail(`agentInstructions.source missing: ${config.source}`)
    return
  }
  if (!sourceStat.isFile()) {
    fail(`agentInstructions.source must be a file: ${config.source}`)
    return
  }

  const actualSourcePath = await realpath(config.sourcePath)
  const actualRepoPath = await realpath(REPO)
  const actualRelative = path.relative(actualRepoPath, actualSourcePath)
  if (actualRelative === '..' || actualRelative.startsWith(`..${path.sep}`) || path.isAbsolute(actualRelative)) {
    fail(`agentInstructions.source resolves outside the repository: ${config.source}`)
    return
  }

  const desired = renderAgentInstructions(config, await readFile(actualSourcePath, 'utf8'))
  const desiredHash = contentHash(desired)
  if (targetExists) {
    const currentHash = contentHash(await readFile(target))
    if (managed === undefined) {
      if (currentHash !== desiredHash) {
        fail(`agent instructions target is unmanaged at ${target}; refusing to overwrite existing content`)
        return
      }
      change(`adopt matching agent instructions ${target}`)
    } else {
      if (typeof managed.deployedHash !== 'string' || currentHash !== managed.deployedHash) {
        fail(`agent instructions drift at ${target}; refusing to overwrite changed managed content`)
        return
      }
      if (currentHash === desiredHash) {
        log('agent instructions up-to-date')
        return
      }
      change(`update agent instructions ${target}`)
      await atomicWrite(target, desired)
    }
  } else {
    if (managed !== undefined) {
      delete state.agentInstructions
      await saveState(state)
      log('cleared stale agentInstructions state before deployment')
    }
    change(`generate agent instructions ${target}`)
    await atomicWrite(target, desired)
  }

  state.agentInstructions = { source: config.source, deployedHash: desiredHash }
  await saveState(state)
}

/**
 * Bundle-less support packages from the top-level `dependencies` list:
 * install / pin / remove as plain profile dependencies. Never join the
 * bundle layer stack (`dsh plugin add` reconciliation already keeps
 * bundle-less packages out); state tracking mirrors managedPackages.
 */
async function syncDependencies(manifest) {
  const state = await loadState()
  const currentNames = new Set(manifest.deps.map((d) => d.name))
  const previousNames = state.managedDependencies ?? []
  for (const name of previousNames) {
    if (currentNames.has(name)) continue
    if (installedVersion(name) !== undefined) {
      change(`remove dependency ${name}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove dependency ${name}`)
    }
  }
  for (const dep of manifest.deps) {
    const current = installedVersion(dep.name)
    if (current !== undefined && current !== dep.version) {
      change(`dependency drift ${dep.name} ${current} -> ${dep.version}, re-adding`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', `${dep.name}@${dep.version}`], { version: manifest.dshVersion })) fail(`failed to pin dependency ${dep.name}`)
    } else if (current === undefined) {
      change(`install dependency ${dep.name} (${dep.spec})`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', dep.spec], { version: manifest.dshVersion })) fail(`failed to install dependency ${dep.name}`)
    } else {
      log(`dependency ${dep.name}@${current} up-to-date`)
    }
  }
  state.managedDependencies = [...currentNames]
  await saveState(state)
}

async function syncPackages(manifest, items) {
  const packages = items.filter((i) => i.type === 'package')
  const enabled = packages.filter((i) => i.enabled)
  const profilePkgPath = path.join(PROFILE_DIR, 'package.json')
  const profilePkg = readJson(profilePkgPath)
  if (profilePkg === undefined) return fail(`profile package.json missing at ${PROFILE_DIR}`)

  const names = new Map()
  for (const item of packages) {
    try { names.set(item.id, npmNameOf(item)) } catch (e) { fail(String(e.message ?? e)) }
  }
  const enabledNames = enabled.map((i) => names.get(i.id)).filter(Boolean)

  // Local package specs embed the absolute checkout path. Repair stale paths
  // before any plugin command so a moved/renamed repository cannot make pnpm
  // fail while reconciling an otherwise unrelated package.
  let repairedLocalSpecs = false
  profilePkg.dependencies ??= {}
  for (const item of enabled.filter((entry) => entry.source === 'local')) {
    const name = names.get(item.id)
    const expected = `file:${path.join(REPO, 'packages', item.id)}`
    if (name !== undefined && profilePkg.dependencies[name] !== expected) {
      change(`local package path ${name} -> ${expected}`)
      profilePkg.dependencies[name] = expected
      repairedLocalSpecs = true
    }
  }
  if (repairedLocalSpecs) await writeJson(profilePkgPath, profilePkg)

  // remove disabled / missing ones first
  for (const [id, name] of names) {
    const item = packages.find((i) => i.id === id)
    if (item.enabled) continue
    if (installedVersion(name) !== undefined) {
      change(`remove disabled package ${name}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove ${name}`)
    }
  }

  // remove entries deleted from the manifest (previously managed, now absent);
  // names now managed as top-level dependencies are not ours to remove
  const state = await loadState()
  const depNames = new Set(manifest.deps.map((d) => d.name))
  const currentNames = new Set(names.values())
  const previousNames = state.managedPackages ?? []
  for (const name of previousNames) {
    if (currentNames.has(name) || depNames.has(name)) continue
    if (installedVersion(name) !== undefined) {
      change(`remove deleted package ${name}`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove ${name}`)
    }
  }
  state.managedPackages = [...currentNames]
  await saveState(state)

  // install / pin-check enabled ones
  for (const item of enabled) {
    const name = names.get(item.id)
    const spec = item.source === 'local' ? `file:${path.join(REPO, 'packages', item.id)}` : item.spec
    const current = installedVersion(name)
    if (current !== undefined && item.source === 'remote' && current !== item.version) {
      change(`version drift ${name} ${current} -> ${item.version}, re-adding`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', item.spec], { version: manifest.dshVersion })) fail(`failed to pin ${name}`)
    } else if (current !== undefined && item.source === 'local' && current !== item.version) {
      change(`local package ${name} ${current} -> ${item.version}, re-adding`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', spec], { version: manifest.dshVersion })) fail(`failed to reinstall ${name}`)
    } else if (current === undefined) {
      change(`install ${item.source} package ${name} (${spec})`)
      if (!dshCli(['plugin', '--profile', PROFILE, 'add', spec], { version: manifest.dshVersion })) fail(`failed to install ${name}`)
    } else {
      log(`package ${name}@${current} up-to-date`)
    }
  }

  // normalize bundles: shipped base (non-managed) entries first, then enabled managed in manifest order.
  // Only bundle-declaring packages join the layer stack: a package without a dsh.bundle manifest
  // is a plain dependency (mirrors `dsh plugin add` reconciliation); forcing it into bundles
  // would fail profile load ("bundle without dsh.bundle manifest").
  const refreshed = readJson(profilePkgPath)
  if (refreshed !== undefined) {
    const managed = new Set([...names.values(), ...(state.managedPackages ?? [])])
    const base = (refreshed.dsh?.profile?.bundles ?? []).filter((b) => !managed.has(b))
    const bundleNames = enabledNames.filter((name) => declaresBundle(name))
    const bundles = [...base, ...bundleNames]
    const before = JSON.stringify(refreshed.dsh?.profile?.bundles ?? [])
    refreshed.dsh ??= {}
    refreshed.dsh.profile ??= {}
    refreshed.dsh.profile.bundles = bundles
    if (JSON.stringify(bundles) !== before) {
      change(`bundles: [${bundles.join(', ')}]`)
      await writeJson(profilePkgPath, refreshed)
    }
    if (JSON.stringify(state.shippedBundles ?? []) !== JSON.stringify(base)) {
      state.shippedBundles = base
      await saveState(state)
    }
  }
}

/**
 * One-click reset: remove every plugin beyond the shipped base set, reset the
 * generated patch layer, and drop synced presets/skills. Reversible via sync.
 */
async function doReset(manifest) {
  const state = await loadState()
  const shipped = state.shippedBundles ?? ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app']
  const profilePkgPath = path.join(PROFILE_DIR, 'package.json')
  const profilePkg = readJson(profilePkgPath)
  if (profilePkg === undefined) return fail(`profile package.json missing at ${PROFILE_DIR}`)

  const bundles = profilePkg.dsh?.profile?.bundles ?? []
  const removable = [...new Set([
    ...bundles.filter((b) => !shipped.includes(b)),
    ...Object.keys(profilePkg.dependencies ?? {}).filter((d) => !shipped.includes(d)),
  ])]
  for (const name of removable) {
    change(`remove plugin ${name}`)
    if (!dshCli(['plugin', '--profile', PROFILE, 'remove', name], { version: manifest.dshVersion })) fail(`failed to remove ${name}`)
  }

  const refreshed = readJson(profilePkgPath) ?? profilePkg
  refreshed.dsh ??= {}
  refreshed.dsh.profile ??= {}
  refreshed.dsh.profile.bundles = shipped
  await writeJson(profilePkgPath, refreshed)

  const target = path.join(PROFILE_DIR, 'cordis.patch.yml')
  const content = GENERATED_HEADER + '\n[]\n'
  if (!existsSync(target) || readFileSync(target, 'utf8') !== content) {
    if (existsSync(target)) await writeFile(target + '.bak', readFileSync(target, 'utf8'))
    change(`reset ${target}`)
    await mkdir(path.dirname(target), { recursive: true })
    await writeFile(target, content)
  }

  for (const key of Object.keys(state)) {
    const m = key.match(/^(preset|skill):(.+)$/)
    if (m === null) continue
    const dst = path.join(DSH_HOME, m[1] === 'preset' ? '.agent-presets' : 'skills', m[2])
    if (existsSync(dst)) {
      change(`remove ${m[1]} ${m[2]}`)
      await rm(dst, { recursive: true, force: true })
    }
    delete state[key]
  }
  delete state.managedPackages
  delete state.managedDependencies
  delete state['managed:preset']
  delete state['managed:skill']
  await saveState(state)
}

async function syncDirs(manifest, items, type, srcDir, dstRoot, requiredFile, label) {
  const state = await loadState()
  const managed = items.filter((i) => i.type === type)
  const enabled = managed.filter((i) => i.enabled)
  for (const item of enabled) {
    const src = path.join(REPO, srcDir, item.id)
    const dst = path.join(dstRoot, item.id)
    if (!existsSync(path.join(src, requiredFile))) {
      fail(`${label} ${item.id}: ${path.join(srcDir, item.id)}/${requiredFile} missing`)
      continue
    }
    const hash = await dirHash(src)
    if (state[`${type}:${item.id}`] === hash && existsSync(path.join(dst, requiredFile))) {
      log(`${label} ${item.id} up-to-date`)
      continue
    }
    change(`copy ${label} ${item.id} -> ${dst}`)
    await rm(dst, { recursive: true, force: true })
    await mkdir(path.dirname(dst), { recursive: true })
    await cp(src, dst, { recursive: true })
    state[`${type}:${item.id}`] = hash
  }
  for (const item of managed.filter((i) => !i.enabled)) {
    const key = `${type}:${item.id}`
    if (state[key] !== undefined) {
      const dst = path.join(dstRoot, item.id)
      if (existsSync(dst)) {
        change(`remove disabled ${label} ${item.id}`)
        await rm(dst, { recursive: true, force: true })
      }
      delete state[key]
    }
  }
  // remove entries deleted from the manifest (previously managed, now absent)
  const currentIds = new Set(managed.map((i) => i.id))
  for (const id of state[`managed:${type}`] ?? []) {
    if (currentIds.has(id)) continue
    const key = `${type}:${id}`
    if (state[key] !== undefined) {
      const dst = path.join(dstRoot, id)
      if (existsSync(dst)) {
        change(`remove deleted ${label} ${id}`)
        await rm(dst, { recursive: true, force: true })
      }
    }
    delete state[key]
  }
  state[`managed:${type}`] = [...currentIds]
  await saveState(state)
}

async function syncPatches(items, manifest) {
  const fragments = items.filter((i) => i.type === 'patch' && i.enabled)
  const target = path.join(PROFILE_DIR, 'cordis.patch.yml')
  const parts = []
  for (const item of fragments) {
    const file = path.join(REPO, 'patches', `${item.id}.yml`)
    if (!existsSync(file)) {
      fail(`patch ${item.id}: patches/${item.id}.yml missing`)
      continue
    }
    parts.push(`# --- fragment: ${item.id} ---\n` + readFileSync(file, 'utf8').trimEnd() + '\n')
  }
  if (resolveWebLan(manifest)) parts.push(LAN_FRAGMENT.trimEnd() + '\n')
  const body = parts.length === 0 ? '[]\n' : parts.join('\n')
  const content = GENERATED_HEADER + '\n' + body
  const existing = existsSync(target) ? readFileSync(target, 'utf8') : ''
  if (existing === content) {
    log('patches up-to-date')
    return
  }
  change(`generate ${target}`)
  if (existing !== '') await writeFile(target + '.bak', existing)
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, content)
}

function logVersion(manifest) {
  log(`dshVersion: ${manifest.dshVersion} (launcher bin/dsh reads dsh.yaml as the single source)`)
}

// ---------- main ----------
async function main() {
  const manifest = loadManifest()
  await mkdir(PROFILE_DIR, { recursive: true })
  if (process.argv.includes('--reset')) {
    await doReset(manifest)
    await syncAgentInstructions(manifest.agentInstructions, { reset: true })
  } else {
    await syncAgentInstructions(manifest.agentInstructions)
    await syncDependencies(manifest)
    await syncPackages(manifest, manifest.items)
    await syncDirs(manifest, manifest.items, 'preset', 'presets', path.join(DSH_HOME, '.agent-presets'), 'agent.cordis.yml', 'preset')
    await syncDirs(manifest, manifest.items, 'skill', 'skills', path.join(DSH_HOME, 'skills'), 'SKILL.md', 'skill')
    await syncPatches(manifest.items, manifest)
  }
  logVersion(manifest)
  console.log('')
  if (failures.length > 0) {
    console.error(`[sync] finished with ${failures.length} failure(s):`)
    for (const f of failures) console.error(`  - ${f}`)
    process.exitCode = 1
    return
  }
  if (changes.length === 0) log('no changes — deployment already matches manifest')
  else log(`done — ${changes.length} change(s) applied`)
}

main().catch((error) => {
  console.error(`[sync] ERROR ${String(error?.message ?? error)}`)
  process.exitCode = 1
})
